// 子代理卡片的两个纯函数（无 React、无 store），便于单测。
import type {
  SubagentActivity,
  SubagentStep,
} from "../../shared/subagent-activity";
import { agentNameZhLabel } from "../../shared/agent-names";

/**
 * 把工具参数里的 agent 引用换成可读的显示名。
 *
 * ⚠️ 两套 id 不是一回事：`subagentActivities` 的 key 是 Agent 工具调用 id
 * （`parentToolCallId`），而参数里的 `agent_id` 对的是快照的 `agentId`（插件 record id）。
 * 所以必须遍历 values 比对，不能写 `activities[ref]`。
 */
export function resolveSubagentName(
  ref: string | undefined,
  activities: Record<string, SubagentActivity> | undefined,
  locale: string,
): string {
  const raw = String(ref ?? "").trim();
  const bare = raw.startsWith("@") ? raw.slice(1) : raw;
  if (!bare) return "";

  const list = activities ? Object.values(activities) : [];
  // 命中 record id 就用它的别名；传的本来就是别名（或没命中）时原样沿用
  const alias = list.find((item) => item.agentId === bare)?.name ?? bare;

  const zhLabel = locale.startsWith("zh") ? agentNameZhLabel(alias) : undefined;
  return zhLabel ?? alias;
}

/**
 * 拆出插件输出的元信息头。
 *
 * 插件的 `get_subagent_result` 输出形如 `Agent: <id>\nType: …\nDescription: …\n\n<正文>`；
 * 而 MessageMarkdown 没开 `breaks`，单换行会被并成一段，所以头部要单独渲染。
 * 规则保守：**只有以 `Agent: ` 开头且含空行时才拆**，其余（`Sent to @hopper`、
 * `Agent failed: …`）整块当正文。
 */
export function splitSubagentOutput(content: string): {
  header?: string;
  body: string;
} {
  if (!content.startsWith("Agent: ")) return { body: content };
  const blank = content.match(/\n[ \t]*\n/);
  if (!blank || blank.index === undefined) return { body: content };
  return {
    header: content.slice(0, blank.index).trimEnd(),
    body: content.slice(blank.index + blank[0].length).trimStart(),
  };
}

/** 状态栏面板的一行。 */
export interface BackgroundAgentRow {
  toolCallId: string;
  name?: string;
  type?: string;
  description?: string;
  status: "running" | "completed" | "error";
  currentLabel?: string;
  stepCount: number;
  durationMs: number;
}

/**
 * 面板里**非运行中**（已完成 / 失败）的行数上限。
 *
 * 一个回合可以 spawn 多个后台子代理（实测一轮 4 个已完成很常见），不封顶的话
 * 面板会一直长长。运行中的行完全不受限——那是用户此刻最关心的。
 * 注意 `error` 也占额度（过滤条件是 `status !== "running"`）。
 */
export const MAX_FINISHED_BACKGROUND_ROWS = 5;

/**
 * 把会话的活动快照整理成面板行。
 * 只收 `background === true`（前台阻塞型卡片就在眼前，不需要入口）；
 * 运行中排前面，组内保持传入顺序——对象键序就是「最近更新」序（store 写入时先删后插）。
 */
export function buildBackgroundAgentRows(
  activities: Record<string, SubagentActivity> | undefined,
  labelFor: (step: SubagentStep) => string,
  locale: string,
  /** 「本轮」白名单；`null` / 未传 = 判不了，不过滤。 */
  currentRoundToolCallIds?: ReadonlySet<string> | null,
): BackgroundAgentRow[] {
  const rows = Object.entries(activities ?? {})
    .filter(([, activity]) => activity.background === true)
    .filter(
      ([toolCallId, activity]) =>
        // 运行中永远保留：跨回合还在跑的不能凭空消失。其余只在本轮集合里才保留。
        activity.status === "running" ||
        !currentRoundToolCallIds ||
        currentRoundToolCallIds.has(toolCallId),
    )
    // 键序 = 最近更新序（store 写入时先删后插 → 最后写入的在末尾）。面板贴底向上长、
    // 首行在最上方，所以反转一下，让刚触发的那个排在最显眼处。
    .reverse()
    .map(([toolCallId, activity]) => {
      const lastStep =
        activity.current ?? activity.steps[activity.steps.length - 1];
      const alias = activity.name;
      const zhLabel =
        alias && locale.startsWith("zh") ? agentNameZhLabel(alias) : undefined;
      return {
        toolCallId,
        name: zhLabel ?? alias,
        type: activity.type,
        description: activity.description,
        status: activity.status,
        currentLabel: lastStep ? labelFor(lastStep) : undefined,
        stepCount: activity.stats.toolUses,
        durationMs: activity.stats.durationMs,
      };
    });

  return [
    ...rows.filter((row) => row.status === "running"),
    // 非运行中的最多留最近 5 条（见 MAX_FINISHED_BACKGROUND_ROWS 的说明）。
    ...rows
      .filter((row) => row.status !== "running")
      .slice(0, MAX_FINISHED_BACKGROUND_ROWS),
  ];
}

/** 跳转需要的最小消息结构：ChatView 的 `displayedMessages` 结构性满足它。 */
export interface JumpMessageLike {
  id: string;
  role: string;
  turnId?: string;
  content: unknown;
  /** 自动续跑注入的 user 消息（不是用户发的），不能当回合边界。 */
  autoGenerated?: boolean;
}

/**
 * 找 toolCallId **所属**的那条消息 —— 也就是这组工具卡片在界面上**开始**的位置。
 *
 * 为什么不是"回合末那条"：一次 spawn 之后的回合往往还会继续好几段（同一回合里继续说话、
 * 再取结果…），而卡片画在**发起这次调用**的那条消息里。取回合末会落在 spawn 的**下一条**
 * 甚至更靠后，实测表现为"跳过去差一点点、还得再往上拖一下"。
 *
 * 必须**复刻渲染层的合并**（`ChatView.tsx:700-746`）：纯工具 assistant 消息（没有 text 块）
 * 若在同 turnId 内**前面**已有 assistant，渲染前会被并进那条、自己没有 DOM 节点。所以返回的
 * id 必须在合并后仍然存在 —— 否则 `handleDockTickSelect` 找不到 `data-message-id`，点击静默失效。
 * 判据用 `turnId` 相等，与渲染层的 `prev.turnId === msg.turnId` 一致（`entries-to-messages` 里
 * 每条消息都带 turnId）。
 */
export function findToolCallOwnerMessageId(
  messages: ReadonlyArray<JumpMessageLike> | undefined,
  toolCallId: string,
): string | null {
  const list = messages ?? [];
  if (!toolCallId) return null;

  const index = list.findIndex(
    (message) =>
      Array.isArray(message.content) &&
      (message.content as Array<{ type?: string; id?: string }>).some(
        (block) => block?.type === "tool_use" && block.id === toolCallId,
      ),
  );
  if (index === -1) return null;

  const owner = list[index];
  const blocksOf = (message: JumpMessageLike) =>
    Array.isArray(message.content)
      ? (message.content as Array<{ type?: string }>)
      : [];
  /** 纯工具消息（没有 text 块）——渲染前会被并进同 turnId 的前一条 assistant。 */
  const isPureToolMessage = (message: JumpMessageLike) => {
    const blocks = blocksOf(message);
    return (
      message.role === "assistant" &&
      blocks.length > 0 &&
      !blocks.some((block) => block?.type === "text")
    );
  };

  const sameTurnId = (message: JumpMessageLike) =>
    message.turnId === owner.turnId;
  let rangeStart = index;
  while (rangeStart > 0 && sameTurnId(list[rangeStart - 1])) rangeStart--;

  // 从回合头走到 owner，重放合并：只保留"会留下自己节点"的那些。
  let survivorId: string | null = null;
  for (let i = rangeStart; i <= index; i++) {
    const message = list[i];
    if (message.role !== "assistant") continue;
    if (isPureToolMessage(message) && survivorId) continue; // 被并走
    survivorId = message.id;
  }
  return survivorId;
}

/**
 * 算「本轮」的 tool_use id 集合 = 最后一条**真实用户消息**之后的所有工具调用。
 *
 * 返回 `null` 表示"判不了"（消息里一条真实用户消息都没有，例如历史还没 hydrate）——
 * 调用方此时**不做过滤**，宁可不收窄也不要误藏。
 */
export function collectCurrentRoundToolCallIds(
  messages: ReadonlyArray<JumpMessageLike> | undefined,
): Set<string> | null {
  const list = messages ?? [];

  let boundary = -1;
  for (let i = list.length - 1; i >= 0; i--) {
    // 自动续跑注入的提示也是 role: "user"，但它不是用户发的，不能当回合边界
    // （否则子代理一完成、通告一注入，刚跑完的就被判成"上一轮"而从面板消失）。
    if (list[i].role === "user" && !list[i].autoGenerated) {
      boundary = i;
      break;
    }
  }
  if (boundary === -1) return null;

  const ids = new Set<string>();
  for (let i = boundary + 1; i < list.length; i++) {
    const { content } = list[i];
    if (!Array.isArray(content)) continue;
    for (const block of content as Array<{ type?: string; id?: string }>) {
      if (block?.type === "tool_use" && block.id) ids.add(block.id);
    }
  }
  return ids;
}

/**
 * 有活动快照时，摘掉上游完成摘要里的统计括号。
 *
 * 上游那句形如 `Agent completed in 221.6s (36 tool uses, 112.7k token) (wrapped up …).`，
 * 括号里的 token 数出自上游的 `getLifetimeTotal`（不含缓存重读），而卡片元信息行现在是
 * 全量口径 —— 同屏两个数会互相打架，且用户无法判断哪个才是真实消耗。
 * 耗时、工具数、token 我们自己的元信息行都有，所以那一组括号是多余的。
 *
 * 只摘**第一个**括号组：后面可能跟着 `(wrapped up at the turn limit — output may be partial)`
 * 这类结论说明，必须留。规则保守：只有以 `Agent completed in ` 开头才动，其余原样返回
 * （`fallbackNote` 前缀、`Agent failed: …`、`Agent queued …` 都不碰）。
 */
export function stripUpstreamAgentStats(content: string): string {
  if (!content.startsWith("Agent completed in ")) return content;
  return content.replace(/\s*\(\d+ tool uses[^)]*\)/, "");
}
