import type {
  CustomMessageEntry,
  SessionEntry,
  SessionMessageEntry,
} from "@earendil-works/pi-coding-agent";
import type {
  ContentBlock,
  Message,
  TextContent,
  ThinkingContent,
  TokenUsage,
  ToolResultContent,
  ToolUseContent,
} from "../../renderer/types";

type PiMessage = SessionMessageEntry["message"];

function isMessageEntry(e: SessionEntry): e is SessionMessageEntry {
  return e.type === "message" && "message" in e;
}

function isAutoGeneratedCustom(e: SessionEntry): e is CustomMessageEntry {
  return e.type === "custom_message" && e.customType === "auto_generated";
}

function toTimestamp(ts: unknown): number {
  if (typeof ts === "number") return ts;
  const parsed = Date.parse(String(ts ?? ""));
  return Number.isFinite(parsed) ? parsed : Date.now();
}

function mapUsage(usage: unknown): TokenUsage | undefined {
  const u = usage as
    | {
        input?: number;
        output?: number;
        cacheRead?: number;
        cacheWrite?: number;
      }
    | undefined;
  if (!u) return undefined;
  // totalPromptInput 在 pi Usage 无对应，用 input 近似（provider-normalized 字段退化，接受）。
  return {
    input: u.input ?? 0,
    output: u.output ?? 0,
    cacheRead: u.cacheRead ?? 0,
    cacheWrite: u.cacheWrite ?? 0,
    totalPromptInput: u.input ?? 0,
  };
}

function mapContentBlock(block: unknown): ContentBlock | null {
  const b = block as { type?: string };
  switch (b.type) {
    case "text":
      return { type: "text", text: (block as TextContent).text };
    case "thinking":
      return {
        type: "thinking",
        thinking: (block as ThinkingContent).thinking,
      };
    case "toolCall": {
      const tc = block as {
        id: string;
        name: string;
        arguments: Record<string, unknown>;
      };
      const out: ToolUseContent = {
        type: "tool_use",
        id: tc.id,
        name: tc.name,
        input: tc.arguments,
      };
      return out;
    }
    case "image": {
      const img = block as { data: string; mimeType: string };
      const mediaType = (img.mimeType || "image/png") as
        | "image/jpeg"
        | "image/png"
        | "image/gif"
        | "image/webp";
      return {
        type: "image",
        source: { type: "base64", media_type: mediaType, data: img.data },
      };
    }
    default:
      return null;
  }
}

function mapContentBlocks(blocks: unknown): ContentBlock[] {
  if (!Array.isArray(blocks)) return [];
  return blocks
    .map(mapContentBlock)
    .filter((b): b is ContentBlock => b !== null);
}

function toolResultText(blocks: unknown): string {
  if (typeof blocks === "string") return blocks;
  return mapContentBlocks(blocks)
    .filter((b): b is TextContent => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

/**
 * Convert pi SessionEntry[] (from PiSessionManager.getEntries()) to the
 * renderer's Message[] representation.
 *
 * - message entries: user/assistant/toolResult → user/assistant/tool_result
 * - custom_message entries with customType "auto_generated" → autoGenerated user
 * - turnId is inferred from the most recent user-role entry id
 */
export function entriesToMessages(
  entries: SessionEntry[],
  sessionId: string,
): Message[] {
  const messages: Message[] = [];
  let currentTurnId: string | undefined;

  for (const entry of entries) {
    if (isAutoGeneratedCustom(entry)) {
      currentTurnId = entry.id;
      messages.push({
        id: entry.id,
        sessionId,
        role: "user",
        content: mapContentBlocks(entry.content),
        timestamp: toTimestamp(entry.timestamp),
        turnId: currentTurnId,
        autoGenerated: true,
      });
      continue;
    }
    if (!isMessageEntry(entry)) continue;

    const msg = entry.message as PiMessage;
    const role = (msg as { role?: string }).role;

    if (role === "user") {
      currentTurnId = entry.id;
      messages.push({
        id: entry.id,
        sessionId,
        role: "user",
        content: mapContentBlocks((msg as { content?: unknown }).content),
        timestamp: toTimestamp((msg as { timestamp?: unknown }).timestamp),
        turnId: currentTurnId,
      });
    } else if (role === "assistant") {
      const a = msg as {
        content?: unknown;
        usage?: unknown;
        timestamp?: unknown;
      };
      messages.push({
        id: entry.id,
        sessionId,
        role: "assistant",
        content: mapContentBlocks(a.content),
        timestamp: toTimestamp(a.timestamp),
        turnId: currentTurnId,
        tokenUsage: mapUsage(a.usage),
      });
    } else if (role === "toolResult") {
      const t = msg as {
        toolCallId?: string;
        content?: unknown;
        isError?: boolean;
        timestamp?: unknown;
        details?: Record<string, unknown>;
      };
      const block: ToolResultContent = {
        type: "tool_result",
        toolUseId: t.toolCallId ?? "",
        content: toolResultText(t.content),
        isError: Boolean(t.isError),
      };
      if (typeof t.details?.diff === "string") block.diff = t.details.diff;
      if (typeof t.details?.errorCode === "string") {
        block.errorCode = t.details.errorCode as ToolResultContent["errorCode"];
      }
      messages.push({
        id: entry.id,
        sessionId,
        role: "assistant",
        content: [block],
        timestamp: toTimestamp(t.timestamp),
        turnId: currentTurnId,
      });
    }
    // 其他 role 跳过
  }
  return messages;
}
