import type {
  CustomMessageEntry,
  SessionEntry,
  SessionMessageEntry,
} from "@earendil-works/pi-coding-agent";
import type {
  ContentBlock,
  Message,
  TextContent,
  ThinkingContent,
  TokenUsage,
  ToolResultContent,
  ToolUseContent,
} from "../../renderer/types";
import type { ElementSelectionRef } from "../../shared/ipc-types";

type PiMessage = SessionMessageEntry["message"];

function isMessageEntry(e: SessionEntry): e is SessionMessageEntry {
  return e.type === "message" && "message" in e;
}

function isAutoGeneratedCustom(e: SessionEntry): e is CustomMessageEntry {
  return e.type === "custom_message" && e.customType === "auto_generated";
}

function toTimestamp(ts: unknown): number {
  if (typeof ts === "number") return ts;
  const parsed = Date.parse(String(ts ?? ""));
  return Number.isFinite(parsed) ? parsed : Date.now();
}

function mapUsage(usage: unknown): TokenUsage | undefined {
  const u = usage as
    | {
        input?: number;
        output?: number;
        cacheRead?: number;
        cacheWrite?: number;
      }
    | undefined;
  if (!u) return undefined;
  // pi 归一化后的 Usage 各分量**互斥**：input 已排除缓存命中/写入
  // （openai-completions: input = prompt_tokens - cacheRead - cacheWrite；
  //   anthropic-messages: input = input_tokens，缓存单独上报）。
  // 因此「完整提示词」= input + cacheRead + cacheWrite ——
  // 与 usage/normalize-usage.ts 对 totalPromptInput 的定义一致，
  // 它同时是缓存命中率与上下文占用百分比的分母。
  const input = u.input ?? 0;
  const cacheRead = u.cacheRead ?? 0;
  const cacheWrite = u.cacheWrite ?? 0;
  return {
    input,
    output: u.output ?? 0,
    cacheRead,
    cacheWrite,
    totalPromptInput: input + cacheRead + cacheWrite,
  };
}

function mapContentBlock(block: unknown): ContentBlock | null {
  const b = block as { type?: string };
  switch (b.type) {
    case "text":
      return { type: "text", text: (block as TextContent).text };
    case "thinking":
      return {
        type: "thinking",
        thinking: (block as ThinkingContent).thinking,
      };
    case "toolCall": {
      const tc = block as {
        id: string;
        name: string;
        arguments: Record<string, unknown>;
      };
      const out: ToolUseContent = {
        type: "tool_use",
        id: tc.id,
        name: tc.name,
        input: tc.arguments,
      };
      return out;
    }
    case "image": {
      const img = block as { data: string; mimeType: string };
      const mediaType = (img.mimeType || "image/png") as
        | "image/jpeg"
        | "image/png"
        | "image/gif"
        | "image/webp";
      return {
        type: "image",
        source: { type: "base64", media_type: mediaType, data: img.data },
      };
    }
    default:
      return null;
  }
}

function mapContentBlocks(blocks: unknown): ContentBlock[] {
  if (!Array.isArray(blocks)) return [];
  return blocks
    .map(mapContentBlock)
    .filter((b): b is ContentBlock => b !== null);
}

function toolResultText(blocks: unknown): string {
  if (typeof blocks === "string") return blocks;
  return mapContentBlocks(blocks)
    .filter((b): b is TextContent => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

/**
 * Convert pi SessionEntry[] (from PiSessionManager.getEntries()) to the
 * renderer's Message[] representation.
 *
 * - message entries: user/assistant/toolResult → user/assistant/tool_result
 * - custom_message entries with customType "auto_generated" → autoGenerated user
 * - turnId is inferred from the most recent user-role entry id
 */
export function entriesToMessages(
  entries: SessionEntry[],
  sessionId: string,
): Message[] {
  const messages: Message[] = [];
  let currentTurnId: string | undefined;
  // 元素引用挂在**下一条** user 消息上（main 把这个条目写在 prompt 之前）。
  const pendingElementRefs: ElementSelectionRef[] = [];

  for (const entry of entries) {
    // 必须放在 isAutoGeneratedCustom **之前**：那个守卫用的是 `entry is CustomMessageEntry`
    // 谓词，会把它的 else 分支收窄成"不是任何 custom_message"，此后任何对
    // custom_message 的判定都会被 TS 判成 never。这里就地判定，不动已有守卫。

    if (
      entry.type === "custom_message" &&
      entry.customType === "browser_element_selection"
    ) {
      // 只认**紧邻**下一条 user 消息的那一条：缓冲在下面每个 message 分支里都会清掉，
      // 所以"元素条目 → 直后就是 user 消息"才成立（runner 正是这个顺序：
      // appendElementContext 在 piSession.prompt 之前）。
      // 反例：回合中途被 abort（appendElementContext 已写、prompt 没发），
      // 那条引用后面跟的是 assistant 而不是 user → 被清掉，不会骑到以后某轮的头上去。
      const details = entry.details as
        | { selections?: ElementSelectionRef[] }
        | undefined;
      const refs = details?.selections;
      if (refs?.length) pendingElementRefs.push(...refs);
      continue;
    }
    if (isAutoGeneratedCustom(entry)) {
      currentTurnId = entry.id;
      messages.push({
        id: entry.id,
        sessionId,
        role: "user",
        content: mapContentBlocks(entry.content),
        timestamp: toTimestamp(entry.timestamp),
        turnId: currentTurnId,
        autoGenerated: true,
      });
      // 悬挂的引用不得骑过自动消息：它属于上一轮，不是这一条
      pendingElementRefs.length = 0;
      continue;
    }
    if (!isMessageEntry(entry)) continue;

    const msg = entry.message as PiMessage;
    const role = (msg as { role?: string }).role;

    if (role === "user") {
      currentTurnId = entry.id;
      messages.push({
        id: entry.id,
        sessionId,
        role: "user",
        content: mapContentBlocks((msg as { content?: unknown }).content),
        timestamp: toTimestamp((msg as { timestamp?: unknown }).timestamp),
        turnId: currentTurnId,
        // 投影（不是 XML）：气泡里的 chip 靠它渲染
        elSelections: pendingElementRefs.length
          ? [...pendingElementRefs]
          : undefined,
      });
      pendingElementRefs.length = 0;
    } else if (role === "assistant") {
      // 悬挂的引用不能跨回合：assistant 出现说明没有 user 消息接手，丢弃
      pendingElementRefs.length = 0;
      const a = msg as {
        content?: unknown;
        usage?: unknown;
        timestamp?: unknown;
      };
      messages.push({
        id: entry.id,
        sessionId,
        role: "assistant",
        content: mapContentBlocks(a.content),
        timestamp: toTimestamp(a.timestamp),
        turnId: currentTurnId,
        tokenUsage: mapUsage(a.usage),
      });
    } else if (role === "toolResult") {
      const t = msg as {
        toolCallId?: string;
        content?: unknown;
        isError?: boolean;
        timestamp?: unknown;
        details?: Record<string, unknown>;
      };
      const block: ToolResultContent = {
        type: "tool_result",
        toolUseId: t.toolCallId ?? "",
        content: toolResultText(t.content),
        isError: Boolean(t.isError),
      };
      if (typeof t.details?.diff === "string") block.diff = t.details.diff;
      if (typeof t.details?.errorCode === "string") {
        block.errorCode = t.details.errorCode as ToolResultContent["errorCode"];
      }
      messages.push({
        id: entry.id,
        sessionId,
        role: "assistant",
        content: [block],
        timestamp: toTimestamp(t.timestamp),
        turnId: currentTurnId,
      });
    }
    // 其他 role 跳过
  }
  return messages;
}

/**
 * 定位分叉点 entry id：messages（entriesToMessages 转换 + 实时追加）与 entries
 * 顺序一致；遍历 entries，跳过非 message 的 entry（compaction/label 等），
 * autoGenerated custom_message 计入（它会被转成 user 消息）。第 forkIdx 条即分叉点。
 */
export function locateForkEntryId(
  entries: SessionEntry[] | null,
  forkIdx: number,
): string | null {
  if (!entries) return null;
  let msgIdx = 0;
  for (const entry of entries) {
    const isMessage =
      entry.type === "message" ||
      (entry.type === "custom_message" &&
        entry.customType === "auto_generated");
    if (!isMessage) continue;
    if (msgIdx === forkIdx) return entry.id;
    msgIdx += 1;
  }
  return null;
}
