/**
 * @module main/session/session-manager
 *
 * Session lifecycle manager (957 lines).
 *
 * Responsibilities:
 * - Session CRUD: create, continue, stop, delete, list
 * - Chat history persistence to SQLite via DatabaseInstance
 * - Workspace-scoped sessions with sandbox integration
 * - Delegates AI execution to AgentRunner
 *
 * Dependencies: database, agent-runner, config-store, mcp-manager, sandbox-adapter
 */
import { v4 as uuidv4 } from "uuid";
import * as fs from "fs";
import * as path from "path";
import type {
  Session,
  Message,
  ServerEvent,
  PermissionResult,
  ContentBlock,
  TextContent,
  TraceStep,
  FileAttachmentContent,
} from "../../renderer/types";
import type { DatabaseInstance, TraceStepRow } from "../db/database";
import { PathResolver } from "../sandbox/path-resolver";
import {
  SandboxAdapter,
  getSandboxAdapter,
  initializeSandbox,
  reinitializeSandbox,
} from "../sandbox/sandbox-adapter";
import { SandboxSync } from "../sandbox/sandbox-sync";
import { AgentRunner } from "../agent/agent-runner";
import { resolveModelContextWindow } from "../agent/pi-model-resolution";
import { configStore } from "../config/config-store";
import { DEFAULT_WORKDIR_DIRNAME, getDefaultWorkingDirPath } from "../../shared/workspace-path";
import type { ProviderProfileKey } from "../config/config-store";
import { MCPManager } from "../mcp/mcp-manager";
import { mcpConfigStore } from "../mcp/mcp-config-store";
import { BrowserViewManager } from "../browser/browser-view-manager";
import { AgentRuntimeExtensionManager } from "../extensions/agent-runtime-extension-manager";
import { BackgroundReviewService } from "../agent/background-review";
import { app } from "electron";
import {
  log,
  logError,
  logWarn,
  logCtx,
  logCtxError,
  runWithLogContext,
  generateTraceId,
} from "../utils/logger";
import { maybeGenerateSessionTitle } from "./session-title-flow";
import {
  buildTitlePrompt,
  getDefaultTitleFromPrompt,
  normalizeGeneratedTitle,
} from "./session-title-utils";
import { generateTitleWithAgentSdk } from "../agent/agent-sdk-one-shot";
import { buildScheduledTaskTitle } from "../../shared/schedule/task-title";

interface IAgentRunner {
  run(
    session: Session,
    prompt: string,
    existingMessages: Message[],
    turnId?: string,
  ): Promise<void>;
  cancel(sessionId: string): void;
  clearSdkSession?(sessionId: string): void;
  clearAllSdkSessions?(): void;
  compact(
    sessionId: string,
    instructions?: string,
  ): Promise<"compacted" | "already-compacted" | "skipped">;
  abortCompaction(sessionId: string): void;
  getExtensionCommands?(): { name: string; description: string }[];
  steer?(sessionId: string, text: string): void;
}

const WORKSPACE_MOUNT_VIRTUAL_PATH = "/mnt/workspace";
const TITLE_GENERATION_TIMEOUT_MS = 20000;
const PROVIDER_PROFILE_KEYS: ProviderProfileKey[] = [
  "openrouter",
  "anthropic",
  "deepseek",
  "openai",
  "gemini",
];

function isProviderProfileKey(
  value: string | null | undefined,
): value is ProviderProfileKey {
  if (!value || typeof value !== "string") return false;
  return (
    PROVIDER_PROFILE_KEYS.includes(value) || value.startsWith("custom:")
  );
}

export class SessionManager {
  private db: DatabaseInstance;
  private sendToRenderer: (event: ServerEvent) => void;
  private pathResolver: PathResolver;
  private sandboxAdapter: SandboxAdapter;
  private agentRunner!: IAgentRunner;
  private mcpManager: MCPManager;
  private extensionManager?: AgentRuntimeExtensionManager;
  private _userSkillsPath: string;
  private browserViewManager: BrowserViewManager | null = null;
  private activeSessions: Map<string, AbortController> = new Map();
  private promptQueues: Map<
    string,
    Array<{ prompt: string; content?: ContentBlock[]; turnId: string; autoGenerated?: boolean }>
  > = new Map();
  private pendingPermissions: Map<string, (result: PermissionResult) => void> =
    new Map();
  private pendingSudoPasswords: Map<
    string,
    { sessionId: string; resolve: (password: string | null) => void }
  > = new Map();
  private sandboxInitPromises: Map<string, Promise<void>> = new Map();
  private sessionTitleAttempts: Set<string> = new Set();
  private titleGenerationTokens: Map<string, symbol> = new Map();
  private messageCache: Map<string, Message[]> = new Map();
  private static readonly MAX_CACHE_SIZE = 100;

  constructor(
    db: DatabaseInstance,
    sendToRenderer: (event: ServerEvent) => void,
    extensionManager?: AgentRuntimeExtensionManager,
  ) {
    this.db = db;
    this.sendToRenderer = (event) => {
      if (event.type === "trace.step") {
        this.saveTraceStep(event.payload.sessionId, event.payload.step);
      }
      if (event.type === "trace.update") {
        this.updateTraceStep(event.payload.stepId, event.payload.updates);
      }
      sendToRenderer(event);
    };
    this.pathResolver = new PathResolver();
    this.sandboxAdapter = getSandboxAdapter();
    this.extensionManager = extensionManager;

    // Store user skills path for lazy BackgroundReviewService creation
    this._userSkillsPath = path.join(app.getPath("home"), ".deskwand", "skills");

    // Initialize MCP Manager
    this.mcpManager = new MCPManager();
    this.initializeMCP();

    // Create agent runner based on current config
    this.createAgentRunner();

    log(
      "[SessionManager] Initialized with persistent database and MCP support",
    );
  }

  /**
   * Create agent runner based on current config
   * Can be called to recreate runner when config changes
   */
  private createAgentRunner(): void {
    this.agentRunner = new AgentRunner(
      {
        sendToRenderer: this.sendToRenderer,
        saveMessage: (message: Message) => this.saveMessage(message),
        requestSudoPassword: (
          sessionId: string,
          toolUseId: string,
          command: string,
        ) => this.requestSudoPassword(sessionId, toolUseId, command),
        turnFinalizer: {
          getReviewService: () => {
            // Lazily create the review service with current config.
            // A fresh instance each time ensures stale config is never used.
            const raw = configStore.getAll();
            return new BackgroundReviewService({
              globalSkillsPath: this._userSkillsPath,
              config: raw,
              pathResolver: this.pathResolver,
            });
          },
        },
      },
      this.pathResolver,
      this.mcpManager,
      undefined, // skillsAdapter
      this.extensionManager,
      this.browserViewManager ?? undefined,
    );
    log("[SessionManager] Using pi-coding-agent runner");
  }

  /**
   * Inject the BrowserViewManager after it has been initialized.
   * The internal browser is created after the session manager, so this
   * must be called once the WebContentsView is ready. Recreates the
   * AgentRunner so it can include internal browser tools.
   */
  setBrowserViewManager(bvm: BrowserViewManager): void {
    this.browserViewManager = bvm;
    this.createAgentRunner();
    log(
      "[SessionManager] BrowserViewManager injected, AgentRunner recreated with internal browser tools",
    );
  }

  /**
   * Notify that API config changed.
   * Model/apiKey/baseUrl changes are picked up per-query via configStore.getAll()
   * and hot-swapped via piSession.setModel(). No need to recreate the runner.
   */
  reloadConfig(): void {
    log("[SessionManager] API config changed — will apply on next query");
  }

  /**
   * Reinitialize MCP servers (call only when MCP config actually changes)
   */
  async reloadMCP(): Promise<void> {
    log("[SessionManager] Reloading MCP servers");
    await this.initializeMCP();
  }

  /**
   * Invalidate cached MCP servers config so the next query rebuilds tools.
   * Call after MCP server add/update/delete.
   */
  invalidateMcpServersCache(): void {
    if (this.agentRunner && "invalidateMcpServersCache" in this.agentRunner) {
      (this.agentRunner as AgentRunner).invalidateMcpServersCache();
    }
  }

  /**
   * Invalidate skills setup so the next query re-links skills.
   * Call after skill install/uninstall/toggle.
   */
  invalidateSkillsSetup(): void {
    if (this.agentRunner && "invalidateSkillsSetup" in this.agentRunner) {
      (this.agentRunner as AgentRunner).invalidateSkillsSetup();
    }
  }

  /** Return extension commands from plugin-loaded extensions (e.g. /subagents-doctor). */
  getExtensionCommands(): { name: string; description: string }[] {
    if (this.agentRunner && "getExtensionCommands" in this.agentRunner) {
      return (this.agentRunner as AgentRunner).getExtensionCommands?.() ?? [];
    }
    return [];
  }

  /**
   * Reinitialize sandbox adapter (call only when sandbox config changes)
   */
  async reloadSandbox(): Promise<void> {
    await this.reinitializeSandboxAsync();
  }

  /**
   * Reinitialize sandbox adapter asynchronously
   */
  private async reinitializeSandboxAsync(): Promise<void> {
    try {
      log("[SessionManager] Reinitializing sandbox adapter...");
      await reinitializeSandbox();
      this.sandboxAdapter = getSandboxAdapter();
      log(
        "[SessionManager] Sandbox adapter reinitialized, mode:",
        this.sandboxAdapter.mode,
      );
    } catch (error) {
      logError("[SessionManager] Failed to reinitialize sandbox:", error);
    }
  }

  /**
   * Initialize MCP servers from configuration
   */
  private async initializeMCP(): Promise<void> {
    try {
      const servers = mcpConfigStore.getEnabledServers();
      await this.mcpManager.initializeServers(servers);
      log(`[SessionManager] Initialized ${servers.length} MCP servers`);
    } catch (error) {
      logError("[SessionManager] Failed to initialize MCP servers:", error);
      this.sendToRenderer({
        type: "error",
        payload: {
          message: `Failed to initialize MCP servers: ${error instanceof Error ? error.message : String(error)}`,
        },
      });
    }
  }

  /**
   * Get MCP manager instance
   */
  getMCPManager(): MCPManager {
    return this.mcpManager;
  }

  /**
   * Get sandbox adapter instance
   */
  getSandboxAdapter(): SandboxAdapter {
    return this.sandboxAdapter;
  }

  // Create and start a new session
  async startSession(
    title: string,
    prompt: string,
    cwd?: string,
    allowedTools?: string[],
    content?: ContentBlock[],
    memoryEnabled?: boolean,
    thinkingLevel?: Session["thinkingLevel"],
    providerProfileKey?: Session["providerProfileKey"],
    model?: string,
    turnId?: string,
  ): Promise<Session> {
    log("[SessionManager] Starting new session:", title);

    const session = this.createSession(
      title,
      cwd,
      allowedTools,
      memoryEnabled,
      thinkingLevel,
      providerProfileKey,
      model,
    );

    // Save to database
    this.saveSession(session);

    // Start processing the prompt with content blocks
    this.enqueuePrompt(session, prompt, content, turnId);

    return session;
  }

  // Create a new session object
  private buildMountedPaths(cwd?: string): Session["mountedPaths"] {
    if (!cwd) {
      return [];
    }
    return [{ virtual: WORKSPACE_MOUNT_VIRTUAL_PATH, real: cwd }];
  }

  private createSession(
    title: string,
    cwd?: string,
    allowedTools?: string[],
    memoryEnabled?: boolean,
    thinkingLevel?: Session["thinkingLevel"],
    providerProfileKey?: Session["providerProfileKey"],
    model?: string,
  ): Session {
    const now = Date.now();
    // Prefer frontend-provided cwd; fallback to app config, then external env vars,
    // then the app's built-in default working directory (userData/default_working_dir).
    const configuredCwd = configStore.get("defaultWorkdir");
    const envCwd = process.env.WORKDIR || process.env.DEFAULT_CWD;
    const builtinDefaultCwd = getDefaultWorkingDirPath(
      app.getPath("userData"),
    );
    const effectiveCwd =
      cwd || configuredCwd || envCwd || builtinDefaultCwd;
    const isProjectMode = !!cwd && path.basename(cwd) !== DEFAULT_WORKDIR_DIRNAME;
    const resolvedMemoryEnabled =
      typeof memoryEnabled === "boolean"
        ? memoryEnabled
        : isProjectMode
          ? false
          : configStore.get("memoryEnabled") !== false;
    return {
      id: uuidv4(),
      title,
      status: "idle",
      cwd: effectiveCwd,
      mountedPaths: this.buildMountedPaths(effectiveCwd),
      allowedTools: allowedTools || [
        "askuserquestion",
        "todowrite",
        "todoread",
        "webfetch",
        "websearch",
        "read",
        "write",
        "edit",
        "list_directory",
        "glob",
        "grep",
      ],
      memoryEnabled: resolvedMemoryEnabled,
      isProjectMode,
      providerProfileKey:
        (providerProfileKey?.trim() as ProviderProfileKey | undefined) ||
        (configStore.get("activeProviderKey") as
          | ProviderProfileKey
          | undefined) ||
        undefined,
      model: model?.trim() || configStore.get("model") || undefined,
      thinkingLevel: thinkingLevel || "medium",
      createdAt: now,
      updatedAt: now,
    };
  }

  // Save session to database
  private saveSession(session: Session) {
    this.db.sessions.create({
      id: session.id,
      title: session.title,
      deskwand_session_id: session.deskWandSessionId || null,
      openai_thread_id: session.openaiThreadId || null,
      status: session.status,
      cwd: session.cwd || null,
      mounted_paths: JSON.stringify(session.mountedPaths),
      allowed_tools: JSON.stringify(session.allowedTools),
      memory_enabled: session.memoryEnabled ? 1 : 0,
      is_project_mode: session.isProjectMode ? 1 : 0,
      provider_profile_key: session.providerProfileKey || null,
      model: session.model || null,
      thinking_level: session.thinkingLevel || "medium",
      archived: 0,
      archived_at: null,
      created_at: session.createdAt,
      updated_at: session.updatedAt,
    });
  }

  // Load session from database
  private loadSession(sessionId: string): Session | null {
    const row = this.db.sessions.get(sessionId);
    if (!row) return null;

    let mountedPaths;
    try {
      mountedPaths = JSON.parse(row.mounted_paths);
    } catch (e) {
      logError("[SessionManager] Failed to parse mounted_paths:", e);
      mountedPaths = [];
    }

    let allowedTools;
    try {
      allowedTools = JSON.parse(row.allowed_tools);
    } catch (e) {
      logError("[SessionManager] Failed to parse allowed_tools:", e);
      allowedTools = [];
    }

    return {
      id: row.id,
      title: row.title,
      deskWandSessionId: row.deskwand_session_id || undefined,
      openaiThreadId: row.openai_thread_id || undefined,
      status: row.status as Session["status"],
      cwd: row.cwd || undefined,
      mountedPaths,
      allowedTools,
      memoryEnabled: row.memory_enabled === 1,
      isProjectMode: row.is_project_mode === 1,
      providerProfileKey: isProviderProfileKey(row.provider_profile_key)
        ? row.provider_profile_key
        : undefined,
      model: row.model || undefined,
      thinkingLevel: (row.thinking_level ||
        "medium") as Session["thinkingLevel"],
      archived: row.archived === 1,
      archivedAt: row.archived_at || undefined,
      createdAt: row.created_at,
      updatedAt: row.updated_at,
    };
  }

  // List all sessions
  listSessions(): {
    sessions: Session[];
    contextWindows: Record<string, number>;
  } {
    const rows = this.db.sessions.getAll();

    const sessions = rows.map((row) => {
      let mountedPaths;

      try {
        mountedPaths = JSON.parse(row.mounted_paths);
      } catch (e) {
        logError("[SessionManager] Failed to parse mounted_paths:", e);
        mountedPaths = [];
      }

      let allowedTools;
      try {
        allowedTools = JSON.parse(row.allowed_tools);
      } catch (e) {
        logError("[SessionManager] Failed to parse allowed_tools:", e);
        allowedTools = [];
      }

      return {
        id: row.id,
        title: row.title,
        deskWandSessionId: row.deskwand_session_id || undefined,
        openaiThreadId: row.openai_thread_id || undefined,
        status: row.status as Session["status"],
        cwd: row.cwd || undefined,
        mountedPaths,
        allowedTools,
        memoryEnabled: row.memory_enabled === 1,
        isProjectMode: row.is_project_mode === 1,
        providerProfileKey: isProviderProfileKey(row.provider_profile_key)
          ? row.provider_profile_key
          : undefined,
        model: row.model || undefined,
        thinkingLevel: (row.thinking_level ||
          "medium") as Session["thinkingLevel"],
        archived: row.archived === 1,
        archivedAt: row.archived_at || undefined,
        createdAt: row.created_at,
        updatedAt: row.updated_at,
      };
    });

    // Resolve contextWindows from model configs for each session
    const contextWindows: Record<string, number> = {};
    for (const s of sessions) {
      const modelName = s.model?.trim();
      if (modelName) {
        try {
          const cw = resolveModelContextWindow(modelName);
          if (cw > 0) {
            contextWindows[s.id] = cw;
          }
        } catch {
          /* skip unresolved */
        }
      }
    }
    return { sessions, contextWindows };
  }

  setSessionThinkingLevel(
    sessionId: string,
    thinkingLevel: Session["thinkingLevel"],
  ): void {
    const existing = this.db.sessions.get(sessionId);
    if (!existing) {
      throw new Error(`Session not found: ${sessionId}`);
    }

    const normalized = thinkingLevel || "medium";
    this.db.sessions.update(sessionId, {
      thinking_level: normalized,
      updated_at: Date.now(),
    });
    this.sendToRenderer({
      type: "session.update",
      payload: { sessionId, updates: { thinkingLevel: normalized } },
    });
  }

  setSessionProviderModel(
    sessionId: string,
    providerProfileKey: Session["providerProfileKey"],
    model: string,
  ): void {
    const normalizedProvider = providerProfileKey?.trim() as
      | ProviderProfileKey
      | undefined;
    const normalized = model.trim();
    if (!normalizedProvider || !normalized) {
      throw new Error("Provider and model are required");
    }

    this.applySessionProviderModel(
      sessionId,
      normalizedProvider,
      normalized,
      true,
    );
  }

  private applySessionProviderModel(
    sessionId: string,
    providerProfileKey?: Session["providerProfileKey"],
    model?: string,
    emitUpdate: boolean = false,
  ): void {
    const existing = this.db.sessions.get(sessionId);
    if (!existing) {
      throw new Error(`Session not found: ${sessionId}`);
    }

    const normalizedProvider = providerProfileKey?.trim() as
      | ProviderProfileKey
      | undefined;
    const normalizedModel = model?.trim();
    if (!normalizedProvider || !normalizedModel) {
      return;
    }

    this.db.sessions.update(sessionId, {
      provider_profile_key: normalizedProvider,
      model: normalizedModel,
      updated_at: Date.now(),
    });

    if (emitUpdate) {
      this.sendToRenderer({
        type: "session.update",
        payload: {
          sessionId,
          updates: {
            providerProfileKey:
              normalizedProvider as Session["providerProfileKey"],
            model: normalizedModel,
          },
        },
      });
    }
  }

  // Continue an existing session
  async continueSession(
    sessionId: string,
    prompt: string,
    content?: ContentBlock[],
    providerProfileKey?: Session["providerProfileKey"],
    model?: string,
    turnId?: string,
  ): Promise<void> {
    log("[SessionManager] Continuing session:", sessionId);

    this.applySessionProviderModel(sessionId, providerProfileKey, model);

    const session = this.loadSession(sessionId);
    if (!session) {
      throw new Error(`Session not found: ${sessionId}`);
    }

    this.enqueuePrompt(session, prompt, content, turnId);
  }

  async generateSessionTitleFromPrompt(prompt: string): Promise<string> {
    const normalizedPrompt = prompt.trim();
    if (!normalizedPrompt) {
      return "New Session";
    }

    const generated = await this.withTimeout(
      this.generateTitleWithConfig(buildTitlePrompt(normalizedPrompt)),
      TITLE_GENERATION_TIMEOUT_MS,
      "session-title-preview",
    );
    const normalizedGenerated = normalizeGeneratedTitle(generated);
    return normalizedGenerated ?? getDefaultTitleFromPrompt(normalizedPrompt);
  }

  async generateScheduledTaskTitle(prompt: string): Promise<string> {
    const sessionTitle = await this.generateSessionTitleFromPrompt(prompt);
    return buildScheduledTaskTitle(sessionTitle);
  }

  /**
   * Ensure sandbox is initialized for the session's workspace
   */
  private async ensureSandboxInitialized(session: Session): Promise<void> {
    if (!session.cwd) {
      log("[SessionManager] No workspace directory, skipping sandbox init");
      return;
    }

    // Check if already initialized with this exact workspace
    if (
      this.sandboxAdapter.initialized &&
      this.sandboxAdapter.workspacePath === session.cwd
    ) {
      return;
    }

    // Check if initialization is already in progress
    const existingPromise = this.sandboxInitPromises.get(session.cwd);
    if (existingPromise) {
      await existingPromise;
      return;
    }

    // Initialize sandbox with workspace
    const initPromise = initializeSandbox({
      workspacePath: session.cwd,
      mainWindow: null, // Will show dialogs globally
    }).then(() => {
      /* void */
    });

    this.sandboxInitPromises.set(session.cwd, initPromise);

    try {
      await initPromise;
      log("[SessionManager] Sandbox initialized for workspace:", session.cwd);
      log("[SessionManager] Sandbox mode:", this.sandboxAdapter.mode);
    } catch (error) {
      logError("[SessionManager] Failed to initialize sandbox:", error);
      this.sendToRenderer({
        type: "error",
        payload: {
          message: `Failed to initialize sandbox: ${error instanceof Error ? error.message : String(error)}`,
        },
      });
      // Continue anyway - sandbox adapter will fallback to native
    } finally {
      this.sandboxInitPromises.delete(session.cwd);
    }
  }

  // Helper: Copy files to session's .tmp directory and sync to sandbox if needed
  private async processFileAttachments(
    session: Session,
    content: ContentBlock[],
  ): Promise<ContentBlock[]> {
    const processedContent: ContentBlock[] = [];

    for (const block of content) {
      if (block.type === "file_attachment") {
        const fileBlock = block as FileAttachmentContent;

        try {
          // Create .tmp directory if it doesn't exist
          // Use session.cwd when available; fall back to userData (always writable)
          // instead of process.cwd() which can be '/' in packaged macOS builds.
          const tmpDir = path.join(
            session.cwd || app.getPath("userData"),
            ".tmp",
          );
          if (!fs.existsSync(tmpDir)) {
            fs.mkdirSync(tmpDir, { recursive: true });
            log("[SessionManager] Created .tmp directory:", tmpDir);
          }

          // Get source file path from the file attachment
          const sourcePath = (fileBlock.relativePath || "").trim(); // This is the full path from Electron
          // IMPORTANT: Use path.basename() to extract only the filename, not the full path
          const fallbackFilename =
            fileBlock.filename || sourcePath || `attachment-${Date.now()}`;
          const destFilename = path.basename(fallbackFilename);
          if (!destFilename) continue;
          const destPath = path.join(tmpDir, destFilename);
          let actualSize = 0;

          // Copy file to .tmp directory
          if (sourcePath && fs.existsSync(sourcePath)) {
            fs.copyFileSync(sourcePath, destPath);

            // Get actual file size
            const stats = fs.statSync(destPath);
            actualSize = stats.size;

            log(
              "[SessionManager] Copied file:",
              sourcePath,
              "->",
              destPath,
              `(${actualSize} bytes)`,
            );
          } else if (fileBlock.inlineDataBase64) {
            const buffer = Buffer.from(fileBlock.inlineDataBase64, "base64");
            fs.writeFileSync(destPath, buffer);
            actualSize = buffer.length;
            log(
              "[SessionManager] Wrote file from inline data:",
              destPath,
              `(${actualSize} bytes)`,
            );
          } else {
            logError(
              "[SessionManager] Source file not found and inline data missing:",
              sourcePath || "(empty path)",
            );
            // Skip this file attachment
            continue;
          }

          // If sandbox is already initialized, sync the file to sandbox as well
          // This handles the case where user attaches files in subsequent messages
          const sandboxPath = SandboxSync.getSandboxPath(session.id);
          if (sandboxPath) {
            const sandboxRelativePath = `.tmp/${destFilename}`;
            log(
              "[SessionManager] Syncing attached file to sandbox:",
              sandboxRelativePath,
            );
            const syncResult = await SandboxSync.syncFileToSandbox(
              session.id,
              destPath,
              sandboxRelativePath,
            );
            if (syncResult.success) {
              log(
                "[SessionManager] File synced to sandbox:",
                syncResult.sandboxPath,
              );
            } else {
              logError(
                "[SessionManager] Failed to sync file to sandbox:",
                syncResult.error,
              );
              // Continue anyway - file is in Windows .tmp, agent might still work via /mnt/
            }
          } else {
            // Check for Lima sandbox
            const { LimaSync } = await import("../sandbox/lima-sync");
            const limaSandboxPath = LimaSync.getSandboxPath(session.id);
            if (limaSandboxPath) {
              const sandboxRelativePath = `.tmp/${destFilename}`;
              log(
                "[SessionManager] Syncing attached file to Lima sandbox:",
                sandboxRelativePath,
              );
              const syncResult = await LimaSync.syncFileToSandbox(
                session.id,
                destPath,
                sandboxRelativePath,
              );
              if (syncResult.success) {
                log(
                  "[SessionManager] File synced to Lima sandbox:",
                  syncResult.sandboxPath,
                );
              } else {
                logError(
                  "[SessionManager] Failed to sync file to Lima sandbox:",
                  syncResult.error,
                );
                // Continue anyway - file is in macOS .tmp, agent might still work via direct access
              }
            }
          }

          // Update the content block with the new relative path and actual size
          const relativePathFromCwd = path.join(".tmp", destFilename);
          const restFileBlock = { ...fileBlock };
          delete restFileBlock.inlineDataBase64;
          processedContent.push({
            ...restFileBlock,
            relativePath: relativePathFromCwd,
            size: actualSize,
          });
        } catch (error) {
          logError("[SessionManager] Error copying file:", error);
          this.sendToRenderer({
            type: "error",
            payload: {
              message: `Failed to process file attachment: ${error instanceof Error ? error.message : String(error)}`,
            },
          });
          // Skip this file attachment
        }
      } else {
        // Keep other content blocks as-is
        processedContent.push(block);
      }
    }

    return processedContent;
  }

  // Process a prompt using AgentRunner
  private async processPrompt(
    session: Session,
    prompt: string,
    content?: ContentBlock[],
    turnId?: string,
    autoGenerated?: boolean,
  ): Promise<void> {
    const traceId = generateTraceId();
    return runWithLogContext({ sessionId: session.id, traceId }, async () => {
      const resolvedTurnId = turnId || uuidv4();
      logCtx(
        "[SessionManager] Processing prompt for session:",
        session.id,
        "traceId:",
        traceId,
      );
      logCtx(
        "[SessionManager] Received content:",
        content
          ? JSON.stringify(
              content.map((c) => ({
                type: c.type,
                hasData: !!(c as { source?: { data?: unknown } }).source?.data,
              })),
            )
          : "none",
      );

      // Ensure sandbox is initialized for this workspace
      await this.ensureSandboxInitialized(session);

      try {
        // Use provided content blocks or fall back to simple text
        let messageContent: ContentBlock[] =
          content && content.length > 0
            ? content
            : [{ type: "text", text: prompt } as TextContent];

        // Process file attachments - copy to .tmp directory
        messageContent = await this.processFileAttachments(
          session,
          messageContent,
        );

        logCtx(
          "[SessionManager] Final message content types:",
          messageContent.map((c) => c.type),
        );

        // Build enhanced prompt with file information
        let enhancedPrompt = prompt;
        const fileAttachments = messageContent.filter(
          (c) => c.type === "file_attachment",
        ) as FileAttachmentContent[];
        if (fileAttachments.length > 0) {
          const fileInfo = fileAttachments
            .map(
              (f) =>
                `- ${f.filename} (${(f.size / 1024).toFixed(1)} KB) at path: ${f.relativePath}`,
            )
            .join("\n");
          enhancedPrompt = `${prompt}\n\n[Attached files - use Read tool to access them]:\n${fileInfo}`;
          logCtx(
            "[SessionManager] Enhanced prompt with file info:",
            enhancedPrompt,
          );
        }

        // ── /goal command interception ─────────────────────────────
        const goalMatch = enhancedPrompt.match(/^\/goal\b\s*(.*)/);
        if (goalMatch && this.extensionManager) {
          const cmdCtx = {
            command: "goal",
            args: goalMatch[1] || "",
            sessionId: session.id,
          };
          const cmdResult = await this.extensionManager.handleCommand(cmdCtx);
          if (cmdResult?.handled) {
            // Save synthetic user message for record-keeping
            const goalUserMsg: Message = {
              id: uuidv4(),
              sessionId: session.id,
              role: "user",
              content: [{ type: "text", text: enhancedPrompt }],
              timestamp: Date.now(),
              turnId: resolvedTurnId,
            };
            this.saveMessage(goalUserMsg);

            // Emit assistant response
            const goalRespMsg: Message = {
              id: uuidv4(),
              sessionId: session.id,
              role: "assistant",
              content: [{ type: "text", text: cmdResult.message ?? "" }],
              timestamp: Date.now(),
              turnId: resolvedTurnId,
            };
            this.saveMessage(goalRespMsg);
            this.sendToRenderer({
              type: "stream.message",
              payload: { sessionId: session.id, message: goalRespMsg },
            });

            // Emit goal status to renderer
            if (cmdResult.goalStatus) {
              this.sendToRenderer({
                type: "goal.status",
                payload: {
                  sessionId: session.id,
                  ...cmdResult.goalStatus,
                },
              });
            }

            // Enqueue first-turn prompt if starting a goal
            if (cmdResult.firstTurnPrompt) {
              this.enqueuePrompt(
                session,
                cmdResult.firstTurnPrompt,
                undefined,
                undefined,
                true,
              );
            }
            return;
          }
        }

        // Save user message to database for persistence
        const existingMessages = this.getMessages(session.id);
        const userMessage: Message = {
          id: uuidv4(),
          sessionId: session.id,
          role: "user",
          content: messageContent, // Save full content including images and files
          timestamp: Date.now(),
          turnId: resolvedTurnId,
        };
        this.saveMessage(userMessage);
        // For auto-generated prompts (goal firstTurn / continue), emit user
        // message to renderer so it can create a pendingTurn for streaming.
        if (autoGenerated) {
          this.sendToRenderer({
            type: "stream.message",
            payload: { sessionId: session.id, message: userMessage },
          });
        }
        logCtx(
          "[SessionManager] User message saved:",
          userMessage.id,
          "with",
          messageContent.length,
          "content blocks",
        );
        const messagesForContext = [...existingMessages, userMessage];

        // Backfill session runtime selection only when the session does not have one yet.
        const currentProviderProfileKey = configStore.get("activeProviderKey");
        const currentModel = configStore.get("model");
        let sessionSelectionChanged = false;
        if (currentProviderProfileKey && !session.providerProfileKey) {
          session.providerProfileKey = currentProviderProfileKey;
          sessionSelectionChanged = true;
        }
        if (currentModel && !session.model) {
          session.model = currentModel;
          sessionSelectionChanged = true;
        }
        if (sessionSelectionChanged) {
          this.db.sessions.update(session.id, {
            provider_profile_key: session.providerProfileKey || null,
            model: session.model || null,
          });
          this.sendToRenderer({
            type: "session.update",
            payload: {
              sessionId: session.id,
              updates: {
                providerProfileKey: session.providerProfileKey,
                model: session.model,
              },
            },
          });
        }

        // Run the agent
        await this.agentRunner.run(
          session,
          enhancedPrompt,
          messagesForContext,
          resolvedTurnId,
        );

        if (this.extensionManager) {
          const stableMessages = this.getMessages(session.id);
          const afterResult = await this.extensionManager
            .afterSessionRun({
              session,
              prompt: enhancedPrompt,
              messages: stableMessages,
            })
            .catch((error) => {
              logCtxError(
                "[SessionManager] Runtime extension post-run hook failed:",
                error,
              );
              return undefined;
            });

          if (afterResult) {
            // Emit goal status to renderer
            if (afterResult.goalStatus) {
              this.sendToRenderer({
                type: "goal.status",
                payload: {
                  sessionId: session.id,
                  ...afterResult.goalStatus,
                },
              });
            }

            // Enqueue continuation prompt for next turn
            if (afterResult.continuePrompt) {
              this.enqueuePrompt(
                session,
                afterResult.continuePrompt,
                undefined,
                undefined,
                true,
              );
            }
          }
        }

        // 标题生成不再与首轮对话并发，避免与主请求竞争同一上游配额/通道导致体感变慢。
        this.runSessionTitleGeneration(session, prompt, existingMessages).catch(
          (err) =>
            logCtxError("[SessionManager] Title generation failed:", err),
        );
      } catch (error) {
        logCtxError("[SessionManager] Error processing prompt:", error);
        const errorText =
          error instanceof Error ? error.message : "Unknown error";
        const alreadyReportedToUser = Boolean(
          error &&
          typeof error === "object" &&
          (error as { alreadyReportedToUser?: boolean }).alreadyReportedToUser,
        );
        if (!alreadyReportedToUser) {
          const assistantMessage: Message = {
            id: uuidv4(),
            sessionId: session.id,
            role: "assistant",
            content: [{ type: "text", text: `**Error**: ${errorText}` }],
            timestamp: Date.now(),
            turnId: resolvedTurnId,
          };
          this.saveMessage(assistantMessage);
          this.sendToRenderer({
            type: "stream.message",
            payload: { sessionId: session.id, message: assistantMessage },
          });
        }
        this.sendToRenderer({
          type: "error",
          payload: { message: errorText },
        });
      }
    }); // end runWithLogContext
  }

  private async runSessionTitleGeneration(
    session: Session,
    prompt: string,
    existingMessages: Message[],
  ): Promise<void> {
    const token = Symbol(`title:${session.id}`);
    this.titleGenerationTokens.set(session.id, token);
    const shouldAbort = () => {
      if (this.titleGenerationTokens.get(session.id) !== token) {
        return true;
      }
      return !this.db.sessions.get(session.id);
    };
    const userMessageCount =
      existingMessages.filter((message) => message.role === "user").length + 1;
    try {
      await maybeGenerateSessionTitle({
        sessionId: session.id,
        prompt,
        userMessageCount,
        currentTitle: session.title,
        hasAttempted: this.sessionTitleAttempts.has(session.id),
        generateTitle: async (titlePrompt) => {
          if (shouldAbort()) {
            return null;
          }
          const title = await this.withTimeout(
            this.generateTitleWithConfig(titlePrompt),
            TITLE_GENERATION_TIMEOUT_MS,
            session.id,
          );
          return normalizeGeneratedTitle(title);
        },
        getLatestTitle: () => this.db.sessions.get(session.id)?.title ?? null,
        markAttempt: () => {
          this.sessionTitleAttempts.add(session.id);
        },
        updateTitle: async (title) => {
          if (shouldAbort()) {
            log(
              "[SessionTitle] Skip update: session no longer active",
              session.id,
            );
            return false;
          }
          const updated = this.updateSessionTitle(session.id, title);
          if (updated) {
            session.title = title;
          }
          return updated;
        },
        shouldAbort,
        log,
      });
    } catch (error) {
      logError("[SessionTitle] Unexpected error", session.id, error);
    } finally {
      if (this.titleGenerationTokens.get(session.id) === token) {
        this.titleGenerationTokens.delete(session.id);
      }
    }
  }

  private async withTimeout<T>(
    promise: Promise<T>,
    timeoutMs: number,
    sessionId: string,
  ): Promise<T | null> {
    return new Promise((resolve) => {
      const timer = setTimeout(() => {
        logError("[SessionTitle] Generation timed out", {
          sessionId,
          timeoutMs,
        });
        resolve(null);
      }, timeoutMs);
      promise
        .then((value) => {
          clearTimeout(timer);
          resolve(value);
        })
        .catch((error) => {
          clearTimeout(timer);
          logError("[SessionTitle] Generation rejected", { sessionId, error });
          resolve(null);
        });
    });
  }

  private async generateTitleWithConfig(
    titlePrompt: string,
  ): Promise<string | null> {
    // Always use pi-ai SDK for title generation
    return normalizeGeneratedTitle(
      await generateTitleWithAgentSdk(titlePrompt, configStore.getAll()),
    );
  }

  private enqueuePrompt(
    session: Session,
    prompt: string,
    content?: ContentBlock[],
    turnId?: string,
    autoGenerated?: boolean,
  ): void {
    const queue = this.promptQueues.get(session.id) || [];
    queue.push({ prompt, content, turnId: turnId || uuidv4(), autoGenerated });
    this.promptQueues.set(session.id, queue);

    if (!this.activeSessions.has(session.id)) {
      this.processQueue(session).catch((err) => {
        logError("[SessionManager] Queue processing error:", err);
        this.sendToRenderer({
          type: "error",
          payload: {
            message: `Failed to process message: ${err instanceof Error ? err.message : String(err)}`,
          },
        });
      });
    } else {
      log("[SessionManager] Session running, queued prompt:", session.id);
    }
  }

  private async processQueue(session: Session): Promise<void> {
    if (this.activeSessions.has(session.id)) return;

    const controller = new AbortController();
    this.activeSessions.set(session.id, controller);
    this.updateSessionStatus(session.id, "running");

    try {
      // Outer loop: after the inner loop drains, re-check for items that
      // arrived while processPrompt was awaited. This keeps the session in
      // activeSessions the entire time, preventing enqueuePrompt from
      // spawning a duplicate processQueue during the gap that previously
      // existed between activeSessions.delete and the restart call.
      let shouldContinue = true;
      while (shouldContinue) {
        while (!controller.signal.aborted) {
          const queue = this.promptQueues.get(session.id);
          if (!queue || queue.length === 0) break;

          const item = queue.shift();
          if (!item) continue;

          const latestSession = this.loadSession(session.id);
          if (!latestSession) {
            log(
              "[SessionManager] Session removed while processing queue:",
              session.id,
            );
            return; // finally handles cleanup
          }

          await this.processPrompt(
            latestSession,
            item.prompt,
            item.content,
            item.turnId,
            item.autoGenerated,
          );

          if (controller.signal.aborted) return; // finally handles cleanup
        }

        // If aborted, exit immediately — finally handles cleanup.
        if (controller.signal.aborted) {
          shouldContinue = false;
          continue;
        }

        // Re-check: items may have been enqueued during the last processPrompt await.
        const pendingQueue = this.promptQueues.get(session.id);
        if (!pendingQueue || pendingQueue.length === 0) {
          shouldContinue = false;
          continue;
        }

        // Reload session before continuing with newly arrived prompts.
        const latestSession = this.loadSession(session.id);
        if (!latestSession) {
          this.promptQueues.delete(session.id);
          shouldContinue = false;
          continue;
        }
        session = latestSession;
        log(
          "[SessionManager] Continuing queue with newly arrived prompts:",
          session.id,
        );
      }
    } finally {
      // Only clean up here — no restart logic needed since the outer loop
      // already handles re-checking. activeSessions is only deleted once
      // there are truly no pending items remaining.
      this.activeSessions.delete(session.id);
      const queue = this.promptQueues.get(session.id);
      if (queue && queue.length === 0) {
        this.promptQueues.delete(session.id);
      }
      this.updateSessionStatus(session.id, "idle");
    }
  }

  // Stop a running session
  stopSession(sessionId: string): void {
    log("[SessionManager] Stopping session:", sessionId);
    this.titleGenerationTokens.delete(sessionId);
    this.agentRunner.cancel(sessionId);
    // Cancel any pending sudo password requests for this session
    for (const [toolUseId, entry] of this.pendingSudoPasswords) {
      if (entry.sessionId === sessionId) {
        entry.resolve(null);
        this.pendingSudoPasswords.delete(toolUseId);
        this.sendToRenderer({
          type: "sudo.password.dismiss",
          payload: { toolUseId },
        });
      }
    }
    // Also abort any pending controller we tracked
    const controller = this.activeSessions.get(sessionId);
    if (controller) {
      controller.abort();
    }
    this.promptQueues.delete(sessionId);
    this.messageCache.delete(sessionId);

    // If processQueue is running, let its finally block handle the idle transition.
    // Otherwise (e.g. stopping an already-idle session), set idle directly.
    if (!controller) {
      this.updateSessionStatus(sessionId, "idle");
    }
  }

  /** Manually compact the conversation for a session. */
  async compactSession(
    sessionId: string,
    instructions?: string,
  ): Promise<"compacted" | "already-compacted" | "skipped"> {
    if (!this.loadSession(sessionId)) throw new Error("Session not found");
    return this.agentRunner.compact(sessionId, instructions);
  }

  /** Abort an in-progress manual compaction for a session. */
  abortCompactionSession(sessionId: string): void {
    if (!this.loadSession(sessionId)) throw new Error("Session not found");
    this.agentRunner.abortCompaction(sessionId);
  }

  /** Inject a steering message during agent execution. */
  steerSession(sessionId: string, text: string): void {
    if (!this.loadSession(sessionId)) throw new Error("Session not found");
    // Steering is a turn-level ephemeral event, not a chat message —
    // do not persist to DB. It lives in the live turn context only.
    this.agentRunner.steer?.(sessionId, text);
  }

  // Delete a session
  async deleteSession(sessionId: string): Promise<void> {
    const existingSession = this.loadSession(sessionId);

    // Stop if running
    this.stopSession(sessionId);

    // Sync and cleanup sandbox if it exists for this session
    if (SandboxSync.hasSession(sessionId)) {
      log("[SessionManager] Cleaning up sandbox for session:", sessionId);
      try {
        await SandboxSync.syncAndCleanup(sessionId);
        log(
          "[SessionManager] Sandbox cleanup complete for session:",
          sessionId,
        );
      } catch (error) {
        logError("[SessionManager] Failed to cleanup sandbox:", error);
        // Continue with session deletion even if sandbox cleanup fails
      }
    }

    // Delete from database (messages will be deleted automatically via CASCADE)
    this.db.sessions.delete(sessionId);
    this.messageCache.delete(sessionId);
    this.sessionTitleAttempts.delete(sessionId);
    this.titleGenerationTokens.delete(sessionId);
    if (this.extensionManager) {
      await this.extensionManager.onSessionDeleted({
        sessionId,
        session: existingSession,
      });
    }

    log("[SessionManager] Session deleted:", sessionId);
  }

  async batchDeleteSessions(sessionIds: string[]): Promise<void> {
    const sessionsById = new Map(
      sessionIds.map(
        (sessionId) => [sessionId, this.loadSession(sessionId)] as const,
      ),
    );
    // Stop sessions and clean up sandboxes first (async, cannot run inside SQLite transaction)
    for (const sessionId of sessionIds) {
      this.stopSession(sessionId);
      if (SandboxSync.hasSession(sessionId)) {
        try {
          await SandboxSync.syncAndCleanup(sessionId);
        } catch (error) {
          logError(
            "[SessionManager] Failed to cleanup sandbox during batch delete:",
            error,
          );
        }
      }
    }

    // Perform all SQLite deletions atomically
    this.db.raw.exec("BEGIN");
    try {
      for (const sessionId of sessionIds) {
        this.db.sessions.delete(sessionId);
        this.messageCache.delete(sessionId);
        this.sessionTitleAttempts.delete(sessionId);
        this.titleGenerationTokens.delete(sessionId);
      }
      this.db.raw.exec("COMMIT");
    } catch (e) {
      this.db.raw.exec("ROLLBACK");
      throw e;
    }

    if (this.extensionManager) {
      for (const sessionId of sessionIds) {
        await this.extensionManager.onSessionDeleted({
          sessionId,
          session: sessionsById.get(sessionId) || null,
        });
      }
    }

    log("[SessionManager] Batch deleted sessions:", sessionIds.length);
  }

  // Archive a single session
  archiveSession(sessionId: string): void {
    const session = this.loadSession(sessionId);
    if (!session) throw new Error("Session not found");

    // Stop if running
    this.stopSession(sessionId);

    this.db.sessions.update(sessionId, {
      archived: 1,
      archived_at: Date.now(),
    });
    log("[SessionManager] Session archived:", sessionId);
  }

  // Unarchive a single session
  unarchiveSession(sessionId: string): void {
    const session = this.loadSession(sessionId);
    if (!session) throw new Error("Session not found");

    this.db.sessions.update(sessionId, {
      archived: 0,
      archived_at: null,
    });
    log("[SessionManager] Session unarchived:", sessionId);
  }

  // Batch archive sessions
  batchArchiveSessions(sessionIds: string[]): void {
    for (const sessionId of sessionIds) {
      this.stopSession(sessionId);
    }
    this.db.raw.exec("BEGIN");
    try {
      const now = Date.now();
      for (const sessionId of sessionIds) {
        this.db.sessions.update(sessionId, { archived: 1, archived_at: now });
      }
      this.db.raw.exec("COMMIT");
    } catch (e) {
      this.db.raw.exec("ROLLBACK");
      throw e;
    }
    log("[SessionManager] Batch archived sessions:", sessionIds.length);
  }

  // Batch unarchive sessions
  batchUnarchiveSessions(sessionIds: string[]): void {
    this.db.raw.exec("BEGIN");
    try {
      for (const sessionId of sessionIds) {
        this.db.sessions.update(sessionId, { archived: 0, archived_at: null });
      }
      this.db.raw.exec("COMMIT");
    } catch (e) {
      this.db.raw.exec("ROLLBACK");
      throw e;
    }
    log("[SessionManager] Batch unarchived sessions:", sessionIds.length);
  }

  // Permanently delete an archived session (reuse deleteSession)
  async permanentDeleteArchivedSession(sessionId: string): Promise<void> {
    return this.deleteSession(sessionId);
  }

  async deleteProjectByCwd(cwd: string): Promise<string[]> {
    const normalizedCwd = cwd.trim().replace(/[\/]+$/, "");
    if (!normalizedCwd) {
      return [];
    }

    const sessionIds = this.listSessions()
      .sessions.filter(
        (session) =>
          (session.cwd || "").trim().replace(/[\\/]+$/, "") === normalizedCwd,
      )
      .map((session) => session.id);

    if (sessionIds.length === 0) {
      return [];
    }

    await this.batchDeleteSessions(sessionIds);
    return sessionIds;
  }

  // Update session status
  private updateSessionStatus(
    sessionId: string,
    status: Session["status"],
  ): void {
    this.db.sessions.update(sessionId, { status, updated_at: Date.now() });

    this.sendToRenderer({
      type: "session.status",
      payload: { sessionId, status },
    });
  }

  private updateSessionTitle(sessionId: string, title: string): boolean {
    const existing = this.db.sessions.get(sessionId);
    if (!existing) {
      log("[SessionTitle] Skip title update for deleted session:", sessionId);
      return false;
    }
    this.db.sessions.update(sessionId, { title });
    this.sendToRenderer({
      type: "session.update",
      payload: { sessionId, updates: { title } },
    });
    return true;
  }

  // Update session's working directory
  // Also clears SDK session cache because Agent SDK sessions are bound to cwd
  updateSessionCwd(sessionId: string, cwd: string): void {
    if (this.activeSessions.has(sessionId)) {
      logWarn(
        "[SessionManager] CWD change requested while session running; stopping active run first",
        { sessionId, cwd },
      );
      this.stopSession(sessionId);
    }
    const mountedPaths = this.buildMountedPaths(cwd);
    // Clear deskwand_session_id in DB so next query creates a new SDK session
    // (Agent SDK sessions cannot change cwd mid-session)
    this.db.sessions.update(sessionId, {
      cwd,
      mounted_paths: JSON.stringify(mountedPaths),
      deskwand_session_id: null,
      openai_thread_id: null,
      updated_at: Date.now(),
    });

    // Also clear the in-memory SDK session cache
    if (this.agentRunner?.clearSdkSession) {
      this.agentRunner.clearSdkSession(sessionId);
    }

    this.sendToRenderer({
      type: "session.update",
      payload: { sessionId, updates: { cwd, mountedPaths } },
    });

    log(
      "[SessionManager] Session cwd updated:",
      sessionId,
      "->",
      cwd,
      "(SDK session cleared)",
    );
  }

  clearAllCachedAgentSessions(): void {
    this.agentRunner?.clearAllSdkSessions?.();
  }

  // Save message to database
  saveMessage(message: Message): void {
    this.db.messages.create({
      id: message.id,
      session_id: message.sessionId,
      role: message.role,
      content: JSON.stringify(message.content),
      timestamp: message.timestamp,
      token_usage: message.tokenUsage
        ? JSON.stringify(message.tokenUsage)
        : null,
      execution_time_ms: message.executionTimeMs ?? null,
      turn_id: message.turnId ?? null,
    });
    const cached = this.messageCache.get(message.sessionId);
    if (cached) {
      cached.push(message);
    } else {
      // Only evict when the cache could actually grow (i.e. the session is
      // not cached yet). Evicting on every saveMessage call is wrong because
      // the Map size didn't increase — we just appended to an existing array —
      // and the oldest entry could be the very session we just updated.
      if (this.messageCache.size > SessionManager.MAX_CACHE_SIZE) {
        const firstKey = this.messageCache.keys().next().value;
        if (firstKey) this.messageCache.delete(firstKey);
      }
      this.messageCache.set(message.sessionId, [message]);
    }

    log("[SessionManager] Message saved:", message.id, "role:", message.role);
  }

  // Get messages for a session
  getMessages(sessionId: string): Message[] {
    const cached = this.messageCache.get(sessionId);
    if (cached) {
      return [...cached];
    }

    const rows = this.db.messages.getBySessionId(sessionId);
    const messages = rows.map((row) => ({
      id: row.id,
      sessionId: row.session_id,
      role: row.role as Message["role"],
      content: this.normalizeContent(row.content),
      timestamp: row.timestamp,
      tokenUsage: row.token_usage ? JSON.parse(row.token_usage) : undefined,
      executionTimeMs: row.execution_time_ms ?? undefined,
      turnId: row.turn_id ?? undefined,
    }));
    this.messageCache.set(sessionId, messages);
    return [...messages];
  }

  private normalizeContent(raw: string): ContentBlock[] {
    try {
      const parsed = JSON.parse(raw) as unknown;
      if (Array.isArray(parsed)) {
        return parsed as ContentBlock[];
      }
      if (
        typeof parsed === "object" &&
        parsed !== null &&
        "type" in parsed &&
        typeof (parsed as { type: unknown }).type === "string"
      ) {
        return [parsed as ContentBlock];
      }
      if (typeof parsed === "string") {
        return [{ type: "text", text: parsed } as TextContent];
      }
      return [{ type: "text", text: String(parsed) } as TextContent];
    } catch {
      return [{ type: "text", text: raw } as TextContent];
    }
  }

  getTraceSteps(sessionId: string): TraceStep[] {
    const rows = this.db.traceSteps.getBySessionId(sessionId);
    const parseToolInput = (
      value: string | null,
    ): Record<string, unknown> | undefined => {
      if (!value) return undefined;
      try {
        return JSON.parse(value) as Record<string, unknown>;
      } catch {
        return undefined;
      }
    };
    return rows.map((row) => ({
      id: row.id,
      type: row.type as TraceStep["type"],
      status: row.status as TraceStep["status"],
      title: row.title,
      content: row.content || undefined,
      toolName: row.tool_name || undefined,
      toolInput: parseToolInput(row.tool_input),
      toolOutput: row.tool_output || undefined,
      isError: row.is_error === 1 ? true : undefined,
      timestamp: row.timestamp,
      duration: row.duration ?? undefined,
    }));
  }

  // Handle permission response
  handlePermissionResponse(toolUseId: string, result: PermissionResult): void {
    const resolver = this.pendingPermissions.get(toolUseId);
    if (resolver) {
      resolver(result);
      this.pendingPermissions.delete(toolUseId);
    }
  }

  // Request permission for a tool
  async requestPermission(
    sessionId: string,
    toolUseId: string,
    toolName: string,
    input: Record<string, unknown>,
  ): Promise<PermissionResult> {
    return new Promise((resolve) => {
      const timeoutId = setTimeout(() => {
        this.pendingPermissions.delete(toolUseId);
        resolve("deny");
        this.sendToRenderer({
          type: "permission.dismiss",
          payload: { toolUseId },
        });
      }, 60_000);
      this.pendingPermissions.set(toolUseId, (result: PermissionResult) => {
        clearTimeout(timeoutId);
        resolve(result);
      });
      this.sendToRenderer({
        type: "permission.request",
        payload: { toolUseId, toolName, input, sessionId },
      });
    });
  }

  // Request sudo password from the user
  async requestSudoPassword(
    sessionId: string,
    toolUseId: string,
    command: string,
  ): Promise<string | null> {
    return new Promise((resolve) => {
      const timeout = setTimeout(() => {
        this.pendingSudoPasswords.delete(toolUseId);
        resolve(null);
        this.sendToRenderer({
          type: "sudo.password.dismiss",
          payload: { toolUseId },
        });
      }, 60_000);
      this.pendingSudoPasswords.set(toolUseId, {
        sessionId,
        resolve: (password: string | null) => {
          clearTimeout(timeout);
          resolve(password);
        },
      });
      this.sendToRenderer({
        type: "sudo.password.request",
        payload: { toolUseId, command, sessionId },
      });
    });
  }

  // Handle sudo password response from renderer
  handleSudoPasswordResponse(toolUseId: string, password: string | null): void {
    const entry = this.pendingSudoPasswords.get(toolUseId);
    if (entry) {
      entry.resolve(password);
      this.pendingSudoPasswords.delete(toolUseId);
    }
  }

  private saveTraceStep(sessionId: string, step: TraceStep): void {
    this.db.traceSteps.create({
      id: step.id,
      session_id: sessionId,
      type: step.type,
      status: step.status,
      title: step.title,
      content: step.content ?? null,
      tool_name: step.toolName ?? null,
      tool_input: step.toolInput ? JSON.stringify(step.toolInput) : null,
      tool_output: step.toolOutput ?? null,
      is_error: step.isError ? 1 : null,
      timestamp: step.timestamp,
      duration: step.duration ?? null,
    });
  }

  private updateTraceStep(stepId: string, updates: Partial<TraceStep>): void {
    const rowUpdates: Partial<TraceStepRow> = {};
    if (updates.type !== undefined) rowUpdates.type = updates.type;
    if (updates.status !== undefined) rowUpdates.status = updates.status;
    if (updates.title !== undefined) rowUpdates.title = updates.title;
    if (updates.content !== undefined) rowUpdates.content = updates.content;
    if (updates.toolName !== undefined) rowUpdates.tool_name = updates.toolName;
    if (updates.toolInput !== undefined) {
      rowUpdates.tool_input = updates.toolInput
        ? JSON.stringify(updates.toolInput)
        : null;
    }
    if (updates.toolOutput !== undefined)
      rowUpdates.tool_output = updates.toolOutput;
    if (updates.isError !== undefined)
      rowUpdates.is_error = updates.isError ? 1 : 0;
    if (updates.timestamp !== undefined)
      rowUpdates.timestamp = updates.timestamp;
    if (updates.duration !== undefined) rowUpdates.duration = updates.duration;

    this.db.traceSteps.update(stepId, rowUpdates);
  }
}
