import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * 结构性守卫：元素引用从 IPC 入口一路透传到 runner，共 5 层 + runner 1 处。
 * 漏掉任何一层都**不会报错**，只会让"重开会话后 chip 消失"——所以用源码断言
 * 把它们都钉住。真正的行为验证在 `tests/element-ref-user-message.test.ts`。
 *
 * 断言一律折行免疫（`\s*` 而不是空格）：这些调用接近 printWidth 80，
 * prettier 折行后硬断言必挂。
 */
const SESSION_MANAGER = readFileSync(
  join(__dirname, "../../main/session/session-manager.ts"),
  "utf8",
);
const RUNNER = readFileSync(
  join(__dirname, "../../main/agent/agent-runner.ts"),
  "utf8",
);

describe("element refs reach the host user message (for SDK details)", () => {
  it("队列项类型带引用", () => {
    expect(SESSION_MANAGER).toContain("elSelections?: ElementSelectionRef[]");
  });

  it("入口两个方法都把引用转发给 enqueuePrompt", () => {
    const forwards = SESSION_MANAGER.match(
      /this\.enqueuePrompt\(\s*session,\s*prompt,\s*content,\s*turnId,\s*undefined,\s*elSelections,?\s*\)/g,
    );
    expect(forwards).toHaveLength(2);
  });

  it("队列项字段被传给 processPrompt", () => {
    expect(SESSION_MANAGER).toMatch(
      /item\.turnId,\s*item\.autoGenerated,\s*item\.elSelections,/,
    );
  });

  it("写进 userMessage，且自动消息不带", () => {
    expect(SESSION_MANAGER).toContain(
      "elSelections: autoGenerated ? undefined : elSelections",
    );
  });

  it("runner 从 lastUserMsg 取引用并交给 appendElementContext", () => {
    expect(RUNNER).toMatch(
      /lastUserMsg\?\.role === "user"\s*\?\s*lastUserMsg\.elSelections/,
    );
    // 同样折行免疫
    expect(RUNNER).toMatch(
      /appendElementContext\(\s*piSession,\s*syntheticContextText,\s*elementRefs,?\s*\)/,
    );
  });
});
