import { describe, expect, it } from "vitest";
import {
  entriesToMessages,
  locateForkEntryId,
} from "../../main/session/entries-to-messages";
import type { SessionEntry } from "@earendil-works/pi-coding-agent";

describe("entriesToMessages", () => {
  it("converts user/assistant/toolResult sequence, inferring turnId", () => {
    const entries = [
      {
        type: "message",
        id: "u1",
        parentId: null,
        timestamp: "2026-08-29T00:00:00.000Z",
        message: {
          role: "user",
          content: [{ type: "text", text: "hi" }],
          timestamp: 1,
        },
      },
      {
        type: "message",
        id: "a1",
        parentId: "u1",
        timestamp: "2026-08-29T00:00:01.000Z",
        message: {
          role: "assistant",
          content: [
            { type: "text", text: "thinking..." },
            {
              type: "toolCall",
              id: "tc1",
              name: "read",
              arguments: { file: "a.ts" },
            },
          ],
          usage: {
            input: 10,
            output: 20,
            cacheRead: 0,
            cacheWrite: 0,
            totalTokens: 30,
            cost: {
              input: 0,
              output: 0,
              cacheRead: 0,
              cacheWrite: 0,
              total: 0,
            },
          },
          timestamp: 2,
        },
      },
      {
        type: "message",
        id: "t1",
        parentId: "a1",
        timestamp: "2026-08-29T00:00:02.000Z",
        message: {
          role: "toolResult",
          toolCallId: "tc1",
          toolName: "read",
          content: [{ type: "text", text: "file contents" }],
          isError: false,
          timestamp: 3,
        },
      },
      {
        type: "message",
        id: "u2",
        parentId: "t1",
        timestamp: "2026-08-29T00:00:03.000Z",
        message: {
          role: "user",
          content: [{ type: "text", text: "next" }],
          timestamp: 4,
        },
      },
    ] as SessionEntry[];

    const messages = entriesToMessages(entries, "s1");

    expect(messages).toHaveLength(4);
    expect(messages[0]).toMatchObject({
      id: "u1",
      sessionId: "s1",
      role: "user",
      content: [{ type: "text", text: "hi" }],
      turnId: "u1",
    });
    expect(messages[1].content).toEqual([
      { type: "text", text: "thinking..." },
      { type: "tool_use", id: "tc1", name: "read", input: { file: "a.ts" } },
    ]);
    expect(messages[1].tokenUsage?.input).toBe(10);
    expect(messages[2]).toMatchObject({
      id: "t1",
      role: "assistant",
      turnId: "u1",
      content: [
        {
          type: "tool_result",
          toolUseId: "tc1",
          content: "file contents",
          isError: false,
        },
      ],
    });
    expect(messages[3].turnId).toBe("u2");
  });

  it("maps autoGenerated custom_message entries", () => {
    const entries = [
      {
        type: "custom_message",
        id: "c1",
        parentId: null,
        timestamp: "2026-08-29T00:00:00.000Z",
        customType: "auto_generated",
        content: [{ type: "text", text: "继续执行目标" }],
        display: false,
      },
    ] as SessionEntry[];

    const messages = entriesToMessages(entries, "s1");
    expect(messages[0]).toMatchObject({
      id: "c1",
      role: "user",
      autoGenerated: true,
      content: [{ type: "text", text: "继续执行目标" }],
    });
  });

  it("skips non-message entries", () => {
    const entries = [
      {
        type: "compaction",
        id: "x1",
        parentId: null,
        timestamp: "t",
        summary: "s",
        firstKeptEntryId: "u1",
        tokensBefore: 10,
      },
      {
        type: "model_change",
        id: "x2",
        parentId: null,
        timestamp: "t",
        provider: "p",
        modelId: "m",
      },
    ] as SessionEntry[] as unknown as SessionEntry[];
    expect(entriesToMessages(entries, "s1")).toEqual([]);
  });
});

describe("locateForkEntryId", () => {
  const entries = [
    {
      type: "message",
      id: "m1",
      parentId: null,
      timestamp: "t1",
      message: { role: "user", content: [], timestamp: 1 },
    },
    {
      type: "compaction",
      id: "c1",
      parentId: "m1",
      timestamp: "t2",
      summary: "s",
      firstKeptEntryId: "m1",
      tokensBefore: 1,
    },
    {
      type: "message",
      id: "m2",
      parentId: "c1",
      timestamp: "t3",
      message: { role: "assistant", content: [], timestamp: 2 },
    },
    {
      type: "custom_message",
      id: "ag1",
      parentId: "m2",
      timestamp: "t4",
      customType: "auto_generated",
      content: [],
      display: false,
    },
  ] as unknown as SessionEntry[];

  it("skips non-message entries and counts autoGenerated custom_message", () => {
    expect(locateForkEntryId(entries, 0)).toBe("m1");
    expect(locateForkEntryId(entries, 1)).toBe("m2");
    expect(locateForkEntryId(entries, 2)).toBe("ag1");
  });

  it("returns null for out-of-range or null entries", () => {
    expect(locateForkEntryId(entries, 3)).toBeNull();
    expect(locateForkEntryId(null, 0)).toBeNull();
  });

  it("stays aligned with entriesToMessages indexing", () => {
    const msgs = entriesToMessages(entries, "s1");
    for (let i = 0; i < msgs.length; i += 1) {
      expect(locateForkEntryId(entries, i)).toBe(msgs[i].id);
    }
  });
});

describe("entriesToMessages 的 usage 口径", () => {
  it("totalPromptInput 是完整提示词（含缓存命中），不是未命中部分", () => {
    // 真实数据形态：deepseek-flash 一轮 input=295 / cacheRead=16000。
    //
    // pi 归一化后的 Usage 各分量**互斥**：
    //   - openai-completions: input = prompt_tokens - cacheRead - cacheWrite（openai-completions.js:1193）
    //   - anthropic-messages: input = input_tokens（Anthropic 本就分开上报缓存）
    // 所以完整提示词 = input + cacheRead + cacheWrite。
    //
    // 这与 usage/normalize-usage.ts 对 totalPromptInput 的定义一致：
    // “the full prompt tokens sent (what counts against the context window)”。
    // 若这里退化成 input，面板的缓存命中率会算成 cacheRead / input：
    // 实测本机 151,370 条 usage 记录里有 122,229 条（81%）满足 cacheRead > input，
    // 于是命中率会显示成几千 %（如 16000 / 295 = 5423%）。
    const entries = [
      {
        type: "message",
        id: "a1",
        parentId: null,
        timestamp: "2026-09-18T00:00:00.000Z",
        message: {
          role: "assistant",
          content: [{ type: "text", text: "ok" }],
          timestamp: 1,
          usage: { input: 295, output: 10, cacheRead: 16000, cacheWrite: 0 },
        },
      },
    ] as SessionEntry[];

    const messages = entriesToMessages(entries, "s1");

    expect(messages[0].tokenUsage?.totalPromptInput).toBe(16295);
    // 三个分量仍是原值（互斥），只有「完整提示词」这一个派生字段需要相加
    expect(messages[0].tokenUsage?.input).toBe(295);
    expect(messages[0].tokenUsage?.cacheRead).toBe(16000);
  });

  it("没有缓存时 totalPromptInput 等于 input", () => {
    const entries = [
      {
        type: "message",
        id: "a1",
        parentId: null,
        timestamp: "2026-09-18T00:00:00.000Z",
        message: {
          role: "assistant",
          content: [{ type: "text", text: "ok" }],
          timestamp: 1,
          usage: { input: 1234, output: 56 },
        },
      },
    ] as SessionEntry[];

    const messages = entriesToMessages(entries, "s1");

    expect(messages[0].tokenUsage?.totalPromptInput).toBe(1234);
    expect(messages[0].tokenUsage?.cacheRead).toBe(0);
  });
});
