import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";

const SCRIPT = path.join(__dirname, "../../../scripts/migrate-messages-to-jsonl.mjs");
function readScript(): string {
  return fs.readFileSync(SCRIPT, "utf-8");
}

describe("migrate-messages-to-jsonl (spec §7)", () => {
  it("contains ZERO_USAGE with cost.total (P0: SDK resume crash guard)", () => {
    expect(readScript()).toContain("total: 0");
  });
  it("skips sessions that already have pi_session_file (idempotent)", () => {
    expect(readScript()).toContain("pi_session_file");
  });
  it("drops autoGenerated rows", () => {
    expect(readScript()).toContain("__autoGenerated__");
  });
});
