import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";

const SRC = path.join(__dirname, "../../main/session/session-manager.ts");
function readSrc(): string {
  return fs.readFileSync(SRC, "utf-8");
}

describe("SessionManager JSONL read path (spec §4.2)", () => {
  it("defines setEntriesReader injection point", () => {
    expect(readSrc()).toContain("setEntriesReader");
  });

  it("getMessages consults readMessagesFromEntries before SQLite", () => {
    const src = readSrc();
    const getMessagesIdx = src.indexOf(
      "getMessages(sessionId: string): Message[]",
    );
    const consultIdx = src.indexOf(
      "readMessagesFromEntries(sessionId)",
      getMessagesIdx,
    );
    expect(getMessagesIdx).toBeGreaterThan(-1);
    expect(consultIdx).toBeGreaterThan(-1);
    expect(consultIdx).toBeGreaterThan(getMessagesIdx);
  });
});

describe("saveMessage narrowing (spec §4.1)", () => {
  it("no longer calls db.messages.create", () => {
    const src = readSrc();
    const saveIdx = src.indexOf("saveMessage(message: Message): void");
    const getMessagesIdx = src.indexOf(
      "getMessages(sessionId: string): Message[]",
    );
    expect(saveIdx).toBeGreaterThan(-1);
    expect(getMessagesIdx).toBeGreaterThan(saveIdx);
    const body = src.slice(saveIdx, getMessagesIdx);
    expect(body).not.toContain("db.messages.create");
    expect(body).toContain("messageCache");
  });
});

describe("synthetic messages runtime-only (spec §5)", () => {
  it("goal/summary/error messages no longer persisted via saveMessage", () => {
    const src = readSrc();
    expect(src).not.toContain("saveMessage(goalUserMsg)");
    expect(src).not.toContain("saveMessage(goalRespMsg)");
    expect(src).not.toContain("saveMessage(summaryMsg)");
    expect(src).not.toContain("saveMessage(respMsg)");
    expect(src).not.toContain("saveMessage(assistantMessage)");
  });
});

describe("forkSession via forkFrom (spec §4.1)", () => {
  it("uses forkSessionFile instead of SQLite message copy", () => {
    const src = readSrc();
    expect(src).toContain("forkSessionFile");
    expect(src).not.toContain("`fork-${newSession.id}");
  });
});

// 背景：后台子代理完成后主进程会往会话里注入一条系统通知继续跑。这条注入
// 消息必须标 autoGenerated，否则它不会发给渲染层，渲染层也就建不出这一轮的
// pendingTurn / activeTurn —— 后果是状态栏空白、正在跑的工具卡看起来像已完成、
// /compact 闸门失效（此接线需要活体 SessionManager，故用源码守卫，与上文同风格）。
describe("background-agent auto-continue", () => {
  it("enqueues the injected prompt as auto-generated", () => {
    const src = readSrc();
    const anchor = src.indexOf("onBackgroundAgentComplete: (sessionId");
    expect(anchor).toBeGreaterThan(-1);
    const body = src.slice(anchor, src.indexOf("this.pathResolver,", anchor));
    expect(body).toMatch(
      /enqueuePrompt\(\s*session,\s*prompt,\s*undefined,\s*undefined,\s*true,?\s*\)/,
    );
  });
});

// 背景：没有任何事情在跑的会话不该是 running。两种残留会让渲染层误以为会话在跑
// （停止按钮常亮、状态栏一直「思考中…」）：扩展桥接建出的会话记录，以及上个
// 进程被强杀时留在 DB 里的 running。
describe("stale running sessions", () => {
  it("createSessionRecord persists an idle session (no prompt yet)", () => {
    const src = readSrc();
    const start = src.indexOf(
      "createSessionRecord(title: string, cwd?: string): Session {",
    );
    const end = src.indexOf("async startSession(", start);
    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    expect(src.slice(start, end)).toContain('session.status = "idle"');
  });

  it("resets stale running statuses at startup, before goals resume", () => {
    const index = fs.readFileSync(
      path.join(__dirname, "../../main/index.ts"),
      "utf-8",
    );
    // 两个调用必须在同一段启动代码里（SessionManager 建好 → SkillsManager 建好
    // 之间），且 reset 在前：recoverGoals 会把 goal 会话真的跑起来。
    const start = index.indexOf("sessionManager = new SessionManager(");
    const end = index.indexOf("skillsManager = new SkillsManager(");
    expect(start).toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    const startupBlock = index.slice(start, end);
    const resetIdx = startupBlock.indexOf("resetStaleRunningStatuses()");
    const recoverIdx = startupBlock.indexOf("recoverGoals()");
    expect(resetIdx).toBeGreaterThan(-1);
    expect(recoverIdx).toBeGreaterThan(resetIdx);
  });
});
