import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";

const SRC = path.join(__dirname, "../../main/agent/agent-runner.ts");
function readSrc(): string {
  return fs.readFileSync(SRC, "utf-8");
}

describe("AgentRunner entriesReader wiring (spec §4.2)", () => {
  it("exposes getSessionEntries for SessionManager entriesReader", () => {
    const src = readSrc();
    expect(src).toContain("getSessionEntries");
  });
});

describe("autoGenerated via sendCustomMessage (spec §6)", () => {
  it("routes autoGenerated prompts through sendCustomMessage", () => {
    const src = readSrc();
    expect(src).toContain("sendCustomMessage");
    expect(src).toContain('customType: "auto_generated"');
    expect(src).toContain("display: false");
  });
});

describe("element context ordering (browser element picking)", () => {
  it("appends the hidden element context before prompting the SDK", () => {
    const src = readSrc();
    // 顺序是硬约束：prompt() 会触发回合，写到它后面 SDK 会把隐藏消息
    // append 到下一个回合，元素就与用户那句话分家了，而且不报错。
    expect(src.indexOf("appendElementContext(")).toBeGreaterThan(-1);
    expect(src.indexOf("appendElementContext(")).toBeLessThan(
      src.indexOf("piSession.prompt("),
    );
  });

  it("never splices element context into the prompt text", () => {
    const src = readSrc();
    // 拼进 prompt / finalPrompt 会破坏 SDK 的 /skill: 识别与模板展开。
    expect(src).not.toContain("syntheticContextText + finalPrompt");
    expect(src).not.toContain("finalPrompt = syntheticContextText");
  });
});
