import { describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";

const SRC = path.join(__dirname, "../../main/agent/agent-runner.ts");
function readSrc(): string {
  return fs.readFileSync(SRC, "utf-8");
}

describe("AgentRunner entriesReader wiring (spec §4.2)", () => {
  it("exposes getSessionEntries for SessionManager entriesReader", () => {
    const src = readSrc();
    expect(src).toContain("getSessionEntries");
  });
});

describe("autoGenerated via sendCustomMessage (spec §6)", () => {
  it("routes autoGenerated prompts through sendCustomMessage", () => {
    const src = readSrc();
    expect(src).toContain("sendCustomMessage");
    expect(src).toContain('customType: "auto_generated"');
    expect(src).toContain("display: false");
  });
});
