// @vitest-environment jsdom
//
// 回归：会话在跑、但渲染层没有 activeTurn 时，输入区状态栏不能空着。
//
// 真实场景（2026-09-25 后台子代理那轮）：后台子代理完成后，主进程
// session-manager 注入系统通知继续对话，这条 user 消息不带 autoGenerated，
// 因此**不会**发给渲染层 —— 渲染层既没有 pendingTurn（提交才会建），
// 也就永远建不出 activeTurn。旧实现把「思考中」闸在 hasActiveTurn 上，
// 于是整轮状态栏空白，只剩一个能停的按钮。
//
// 本文件故意**不** mock ChatInputStatusBar：要断言的正是它真实渲染出的文案。
import React, { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ChatView } from "../../renderer/components/ChatView";
import { useAppStore } from "../../renderer/store";
import type { Message, MountedPath, Session } from "../../renderer/types";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({ t: (key: string) => key, i18n: { language: "en" } }),
}));

vi.mock("../../renderer/hooks/useIPC", () => ({
  useIPC: () => ({
    continueSession: vi.fn(),
    stopSession: vi.fn(),
    forkSession: vi.fn(),
    setSessionThinkingLevel: vi.fn(),
    setSessionProviderModel: vi.fn(),
    getSessionMessagesPage: vi.fn(),
    isElectron: false,
  }),
}));

vi.mock("../../renderer/components/ChatInput", async () => {
  const ReactModule = await import("react");
  return {
    ChatInput: ReactModule.forwardRef(function MockChatInput(_props, ref) {
      ReactModule.useImperativeHandle(ref, () => ({
        clear: () => {},
        focus: () => {},
        setPrompt: () => {},
        submit: () => {},
        isEmpty: () => true,
        selectFiles: () => {},
      }));
      return ReactModule.createElement("div");
    }),
  };
});

vi.mock("../../renderer/components/ChatInputBottomBar", () => ({
  ChatInputBottomBar: () => React.createElement("div"),
}));

function makeSession(status: Session["status"]): Session {
  return {
    id: "s1",
    title: "running session",
    status,
    createdAt: Date.now(),
    updatedAt: Date.now(),
    cwd: "/tmp",
    mountedPaths: [] as MountedPath[],
    allowedTools: [],
    memoryEnabled: false,
    isProjectMode: false,
  };
}

function makeMessage(id: string): Message {
  return {
    id,
    sessionId: "s1",
    role: "user",
    timestamp: Date.now(),
    content: [{ type: "text", text: id }],
  };
}

/** 主进程自动续跑一轮时的渲染层状态：会话 running，但没有 activeTurn。 */
function setInitialState(status: Session["status"]): void {
  useAppStore.setState({
    sessions: [makeSession(status)],
    activeSessionId: "s1",
    sessionStates: {
      s1: {
        historyHydrated: true,
        hasMoreOlder: false,
        oldestMessageId: null,
        messages: [makeMessage("u1")],
        partialByTurn: {},
        partialMessage: "",
        partialThinking: "",
        pendingTurns: [],
        activeTurn: null,
        executionClock: { startAt: null, endAt: null },
        traceSteps: [],
        contextWindow: 0,
        compaction: { status: "idle" },
        retry: { active: false, attempt: 0 },
        inputQueue: [],
        steerRecords: [],
        partialToolResults: {},
        backgroundAgents: [],
        subagentActivities: {},
      },
    },
  });
}

describe("ChatView input status for a running session without a renderer turn", () => {
  let container: HTMLDivElement;
  let root: Root;
  let scrollToDescriptor: PropertyDescriptor | undefined;

  beforeEach(() => {
    (
      globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
    ).IS_REACT_ACT_ENVIRONMENT = true;
    useAppStore.setState(useAppStore.getInitialState());
    class ResizeObserverMock {
      observe() {}
      disconnect() {}
      unobserve() {}
    }
    vi.stubGlobal("ResizeObserver", ResizeObserverMock);
    vi.stubGlobal("requestAnimationFrame", (callback: FrameRequestCallback) => {
      callback(0);
      return 1;
    });
    vi.stubGlobal("cancelAnimationFrame", () => {});
    scrollToDescriptor = Object.getOwnPropertyDescriptor(
      HTMLElement.prototype,
      "scrollTo",
    );
    Object.defineProperty(HTMLElement.prototype, "scrollTo", {
      configurable: true,
      writable: true,
      value: () => {},
    });
    container = document.createElement("div");
    document.body.appendChild(container);
    root = createRoot(container);
  });

  afterEach(async () => {
    await act(async () => root.unmount());
    container.remove();
    vi.unstubAllGlobals();
    if (scrollToDescriptor) {
      Object.defineProperty(
        HTMLElement.prototype,
        "scrollTo",
        scrollToDescriptor,
      );
    } else {
      delete (
        HTMLElement.prototype as unknown as {
          scrollTo?: HTMLElement["scrollTo"];
        }
      ).scrollTo;
    }
  });

  it("shows the processing indicator while the session runs without an active turn", async () => {
    setInitialState("running");
    await act(async () => root.render(React.createElement(ChatView)));

    expect(container.textContent ?? "").toContain("chat.processing");
  });

  it("still shows nothing once the session is idle", async () => {
    setInitialState("idle");
    await act(async () => root.render(React.createElement(ChatView)));

    expect(container.textContent ?? "").not.toContain("chat.processing");
  });
});
