import { describe, expect, it } from "vitest";
import {
  mergeSteerEntries,
  resolveAnchorMessageId,
} from "../../renderer/steer-entries";
import type { SteerRecord } from "../../renderer/types";

const record = (
  id: string,
  ts: number,
  status: SteerRecord["status"],
  anchorMessageId?: string,
): SteerRecord => ({
  id,
  text: `text-${id}`,
  status,
  ts,
  anchorMessageId,
});

describe("mergeSteerEntries", () => {
  it("positions record after its anchor message, ignoring later timestamps", () => {
    // 注入发生在 m1 之后（anchor=m1）；m2 完成时刻（900）晚于记录 ts（500）——
    // 纯 ts 排序会把记录排到 m1 前面，锚点语义必须把它固定在 m1 与 m2 之间。
    const entries = [
      { id: "m1", message: { id: "m1", timestamp: 800 } },
      { id: "m2", message: { id: "m2", timestamp: 900 } },
    ];
    const records = [
      record("s1", 500, "delivered", "m1"),
    ];
    expect(mergeSteerEntries(entries, records).map((e) => e.id)).toEqual([
      "m1",
      "s1",
      "m2",
    ]);
  });

  it("keeps record after its anchor on equal positions", () => {
    const entries = [{ id: "m1", message: { id: "m1", timestamp: 100 } }];
    const records = [record("s1", 100, "delivered", "m1")];
    expect(mergeSteerEntries(entries, records).map((e) => e.id)).toEqual([
      "m1",
      "s1",
    ]);
  });

  it("renders records even when the message list is empty", () => {
    const records = [record("s1", 100, "failed")];
    expect(mergeSteerEntries([], records)).toHaveLength(1);
  });

  it("preserves relative order of multiple records with the same anchor", () => {
    const entries = [{ id: "m1", message: { id: "m1", timestamp: 100 } }];
    const records = [
      record("s1", 150, "delivered", "m1"),
      record("s2", 250, "failed", "m1"),
    ];
    expect(mergeSteerEntries(entries, records).map((e) => e.id)).toEqual([
      "m1",
      "s1",
      "s2",
    ]);
  });

  it("falls back to the end when the anchor message is not in the window", () => {
    const entries = [{ id: "m1", message: { id: "m1", timestamp: 100 } }];
    const records = [record("s1", 50, "delivered", "missing")];
    expect(mergeSteerEntries(entries, records).map((e) => e.id)).toEqual([
      "m1",
      "s1",
    ]);
  });
});

describe("resolveAnchorMessageId", () => {
  const msg = (id: string, role: "user" | "assistant", turnId?: string, autoGenerated?: boolean) => ({
    id,
    role,
    turnId,
    autoGenerated,
  });

  it("returns the first assistant message id of the turn when the last message is a later assistant message", () => {
    const messages = [
      msg("u1", "user"),
      msg("a1", "assistant", "turn-1"), // 回合第一条（合并后保留 id）
      msg("a2", "assistant", "turn-1"), // 纯工具消息，会被合并、id 消失
    ];
    expect(resolveAnchorMessageId(messages as never)).toBe("a1");
  });

  it("returns the last user message id as-is", () => {
    const messages = [msg("u1", "user"), msg("u2", "user")];
    expect(resolveAnchorMessageId(messages as never)).toBe("u2");
  });

  it("returns the assistant id when it is the only message of its turn", () => {
    const messages = [msg("u1", "user"), msg("a1", "assistant", "turn-1")];
    expect(resolveAnchorMessageId(messages as never)).toBe("a1");
  });

  it("skips auto-generated trailing messages", () => {
    const messages = [
      msg("u1", "user"),
      msg("a1", "assistant", "turn-1"),
      msg("g1", "user", undefined, true),
    ];
    expect(resolveAnchorMessageId(messages as never)).toBe("a1");
  });

  it("returns undefined for an empty list", () => {
    expect(resolveAnchorMessageId([])).toBeUndefined();
  });
});

describe("resolveAnchorMessageId text-bearing assistant", () => {
  const withContent = (
    id: string,
    role: "user" | "assistant",
    turnId: string | undefined,
    content: Array<{ type: string }>,
  ) => ({ id, role, turnId, content });

  it("anchors to the last message itself when it is a text-bearing assistant message (it survives the merge)", () => {
    const messages = [
      { id: "u1", role: "user" as const },
      { id: "a1", role: "assistant" as const, turnId: "turn-1" },
      withContent("a2", "assistant", "turn-1", [{ type: "text" }]),
    ];
    expect(resolveAnchorMessageId(messages as never)).toBe("a2");
  });

  it("anchors to the first assistant of the turn when the last message is a pure-tool message", () => {
    const messages = [
      { id: "u1", role: "user" as const },
      { id: "a1", role: "assistant" as const, turnId: "turn-1" },
      withContent("a2", "assistant", "turn-1", [{ type: "tool_result" }]),
    ];
    expect(resolveAnchorMessageId(messages as never)).toBe("a1");
  });
});
