import type { Message, SteerRecord } from "./types";

/** 消息流条目（visibleTurnEntries 的元素），含 message.id/timestamp。 */
export type MessageTimelineEntry = { message: { id: string; timestamp: number } };

/**
 * 计算引导记录的锚点消息 id：注入时刻最后一条可见消息；若它是 assistant
 * 消息且属于某个回合，锚点取**该回合第一条 assistant 消息**的 id——渲染时
 * 同 turnId 的 assistant 消息会合并到第一条（保留第一条 id），锚到被合并
 * 的消息会在渲染窗口找不到而 fallback 沉底。
 */
export function resolveAnchorMessageId(
  messages: Message[],
): string | undefined {
  const lastVisible = [...messages].reverse().find((m) => !m.autoGenerated);
  if (!lastVisible) return undefined;
  if (lastVisible.role === "assistant" && lastVisible.turnId) {
    // 只有纯工具消息（无文本块）会被渲染管线合并进同回合第一条 assistant
    //（保留第一条 id）——有文本的消息保留自身 id，可直接作锚点。
    const hasText = Array.isArray(lastVisible.content)
      ? lastVisible.content.some((b) => b.type === "text")
      : false;
    if (!hasText) {
      const firstOfTurn = messages.find(
        (m) => m.role === "assistant" && m.turnId === lastVisible.turnId,
      );
      if (firstOfTurn) return firstOfTurn.id;
    }
  }
  return lastVisible.id;
}

/**
 * 将引导记录按"注入位置"合并进消息流：记录插在其锚点消息（注入时刻消息流
 * 最后一条可见消息）之后。不用纯时间戳排序——消息 timestamp 是完成时刻语义，
 * 回合完成时会导致记录相对位置跳变。同锚点多条记录保持数组序（ts 序）；
 * 无锚点或锚点不在渲染窗口内 → 排在消息流末尾。
 */
export function mergeSteerEntries<E extends MessageTimelineEntry>(
  entries: E[],
  records: SteerRecord[],
): Array<E | SteerRecord> {
  if (records.length === 0) return entries;
  const indexByMessageId = new Map<string, number>();
  entries.forEach((entry, index) => {
    indexByMessageId.set(entry.message.id, index);
  });
  const tailPos = entries.length;
  const positioned: Array<{ pos: number; item: E | SteerRecord }> = entries.map(
    (entry, index) => ({ pos: index, item: entry }),
  );
  for (const record of records) {
    const anchorIndex = record.anchorMessageId
      ? indexByMessageId.get(record.anchorMessageId)
      : undefined;
    positioned.push({
      pos: anchorIndex !== undefined ? anchorIndex + 0.5 : tailPos + 0.5,
      item: record,
    });
  }
  // 稳定排序：同 pos（同锚点 / 同 fallback 位）保持 push 顺序（= ts 序）
  positioned.sort((a, b) => a.pos - b.pos);
  return positioned.map((p) => p.item);
}
